### ISSUE TITLE
LukeKK (nintynick)

### ISSUE THREAD

**Issue by nintynick** [raid-guild/RIPs#100]
### Championee

LukeKK

### Champion

nintynick

## Summary of work to date

Luke participated in the Season 4 Cohort, during which he:
- Assisted with editing State of the Raid (https://raidguild.substack.com/p/state-of-the-raid-april-2022)
- Wrote article about RaidGuild experience (https://hackmd.io/@raidguild/HJfd53ek5/%2FreQv7OnxTIe_gatwDLtfag) 
- Created the Treasury of the Commons proposal deck (https://docs.google.com/presentation/d/1qzpRY6z6CfSub6sr_Bs9Tld_BqeThbqdW6Ghhs0dpKs/edit?usp=sharing) and walkthrough video
- Helpd with the scoping call with METL, RaidGuild client, about marketing advisory services through Shill Shop
- Showed up on a bunch of RaidGuild calls including the full Season 4 process and some internal calls (e.g. Shill Shop, Roundup, Token Talk) to gain exposure.

Luke has also already been leading RIP #89 (including the completion of Phase 1) with me and doing strong work (see RIP for more details).

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

https://blockscout.com/xdai/mainnet/tx/0xa362d409115cb7642131228935dd0ecd65282073a82e61032fc71f52f8546258

## Anything else you'd like to add?

Luke's introduction of himself in discord: https://discord.com/channels/684227450204323876/935329716292943872/955895247546773535

Luke and I have a long-standing friendship and existing professional experience together - I can vouch for him even beyond his work within Raid Guild so far.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
Just wanted to document that the Apprenticeship for this ends Monday, September 5, 2022

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/376

**Comment by plor** [comment]
https://gnosis.blockscout.com/tx/0x4c1304ffdd85e9f7faa73b5de9e69ff7152086dd503825c649eb4673e05df44a
