### ISSUE TITLE
Jip (Sasquatch)

### ISSUE THREAD

**Issue by IanBoucherTru** [raid-guild/RIPs#101]
### Championee

Jip (Jip#3953)

### Champion

Sasquatch

## Summary of work to date

Cohort member from Season 3, Jip has shown his work ethic and dedication to RG. For a cohort project worked on the POAP Quiz app. As an apprentice Jip worked as a Warrior building out the FrontEnd of the STOA mediation dApp, mobile and desktop. Jip was a constant and dedicated contributor to this project even though the timeline extended well past the original budgeted. Showed a true determination to shipping the project.  

Accomplishments:
+ Participation in Cohort 3
+ POAP Quiz Cohort Project
+ STOA Raid (Meditation dApp)

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[link to the staking transaction here](https://blockscout.com/xdai/mainnet/tx/0x3cbff689bd50abc4e1dd943c3a50af323105eb9c17cab2ad5c560095f4fe0f84)

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
Apprenticeship period ends: Friday, September 16, 2022

**Comment by plor** [comment]
I just processed your proposal, you're now a member. Collab.land should pick this up normally, but you can force update it if you want the member role immediately. https://blockscout.com/xdai/mainnet/tx/0x51810d9fee5aa0d2a4aab1c59ef110eeadf18e76c72e9520aa25a03ccc3ccb26

Ready for champion reward now.

**Comment by ECWireless** [comment]
Closing since this is over a year old
