### ISSUE TITLE
nintynick (spencer)

### ISSUE THREAD

**Issue by spengrah** [raid-guild/RIPs#102]
### Championee

nintynick

### Champion

spencer

## Summary of work to date

As of 4/7/22...
- Nick attended nearly all of the token talks since his membership proposal passed on Dec 4 2021 (has missed ~3 total), and attended the first 5 roundtables after he joined and then stopped keeping track since he was attending consistently.
- Nick is in good standing on the availability-n-commitments RIP.

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

https://blockscout.com/poa/xdai/tx/0x4683a3f2c18506d4cb6752b0fb2299bd200e920dc2e0d77f585f2ef35352e9f8

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by ECWireless** [comment]
Closing since this is over a year old
