### ISSUE TITLE
starrdev (scottrepreneur)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#107]
### Championee

starrdev

### Champion

scottrepreneur

## Summary of work to date

Participated in rite of moloch and other s5 projects

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [x] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[link to the staking transaction here](https://gnosisscan.io/tx/0xe90f4c287b2a4c07010f77be06a86d5a859c79ec3202bb07705139f44cfadf1a)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
Apprenticeship starts today, eligibility for membership starts on Sunday, December 11 and must be completed by Thursday, February 9.

**Comment by personnamedmike** [comment]
This RIP is finished. I'm also be doing frontend work on the Rite of Moloch v2 RIP (RIP still pending approval)

**Comment by plor** [comment]
~2 weeks until you can request membership. I hope the apprenticeship is going well for you.

**Comment by plor** [comment]
@personnamedmike your membership window is now open. you can put in a membership proposal anytime from now until February 9. Let me know if you need any help.

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/401

**Comment by ECWireless** [comment]
Closing since this is over a year old
