### ISSUE TITLE
RIP: Escrow RIP funds

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#109]
# Project Idea

### Project Submitted By

@bitbeckers 

## Summary

To increase insight and accountability on RIP progression, we propose to add a escrow mechanism the the RIP funding process. In short, funds would be released when the RIP is delivered according to the defined requirements and when approved by the guild via voting.

## Changes

Quoting @scottrepreneur :
> I think the big thing here is a process update which would likely need to update the 🌴│handbook. Basically give folks the option to
> 1. use a shared safe minion with a DAO or hat-based gnosis safe
> 2. use smart invoice/escrow

In both cases, RG DAO would have signing/release power.

### RIP funding process

1. After a RIP is accepted we expect the address of a minion or escrow details to be in the proposal.
2. When the RIP proposal is accepted, funds are transfered to the minion/escrow
3. RIP party works, parties, meanders, delivers
4. RIP is put to 'Review' status (and discussed during RT). Review would fit on the project flow between 'In Progress' and 'Finalized'
5. After review a DAO proposal is made to release the funds from minion/escrow
6. DAO votes and executes.

Hot stretch: we could add deadlines with possible penalties?

#### Shared Minion
 Quoting @scottrepreneur :
 > using the shared minion safe would mean the DAO can use the funds in another way or return them to the treasury. it'd be assumed that if the team pre-maturely moved the funds from the safe they would be subject to ragekick.

#### Smart Invoice/Escrow
From Smart Invoice FAQ:
> If there is a dispute, you or your client can “lock” funds held by that invoice. This lock triggers the arbitration provider (LexDAO, or the custom provider you chose) to review and resolve the dispute. Based on the arbitrator’s review, they will determine who should receive funds and will send a transaction to Smart Invoice that transfers those funds to you or your client. Our recommended arbitrator, LexDAO, currently charges a 5% fee that is automatically deducted from the funded milestone for their arbitration services.

### Handbook entry

Reference: [RIPs | RaidGuild Handbook](https://handbook.raidguild.org/docs/rips)

* Add `Deliverable` segment that emcompasses the following points:
    * Like on Raids, the deliverable of the RIP will be subject to client review
    * To align expectations and prevent disputes clearly outline the deliverable and a definition of complete (see example below).
* Add `Process` segment that clearly outlines the steps described above
* Add `Escrow` segment that points to and explains the option for using a) Smart Escrow and b) shared minion
* Add `Disputes` segment that outlines the impact of disputes and the proces that will follow

## Why should we build this?

* During the JokeDAO voting a lack of accountability emerged as one of the key issues we should work on
* Alligning monetary incentives has been proposed as a proper solution
* Currently, the RIP party receives all funding before delivering or even starting work
* Injecting escrow mechanisms incentives a review on the deliverable by the guild
* Incentivising review motivates defining clear deliverables.

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Stamina
- Verboseness

## Deliverable

- [ ] Updated handbook with entries for Deliverable, Process, Escrow and Disputes as outlined above.
- [ ] Dry run with Smart Invoice to validate steps
- [ ] Dry run with shared minion to validate steps

[Handbook PR](https://github.com/raid-guild/handbook/pull/79)

## Cost (in USD)

$0.00. Zero. Nada. Niets.

## Proposal:

https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/384

**Comment by Tropical-Wilson** [comment]
Why so free? Seems valuable work - I guess guild decreed retroactive possible

**Comment by plor** [comment]
Is there anything needed here to finalize this RIP? It has been hanging out in "In Progress" for a while.

**Comment by plor** [comment]
@bitbeckers it seems that this could benefit from a `PROPOSALS/RIP-109.md` but if you don't think so feel free to close.
