### ISSUE TITLE
Dungeon Master v2 Discovery & UX

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#111]
## Overview

- Dungeon Master (DM) has been incubated within RaidGuild since the Season 1 cohort.
- Many raiders have hacked on it through various configurations.
- The tool is currently not being used, but we lack clarity as to precisely why this is.
- If successful, this RIP promises to increase the coordination of the guild and provide a powerful white label product offering for the larger ecosystem, opening up numerous collaboration and funding opportunities.

## Problem

- There is an abundance of information/knowledge to share across the guild that we struggle to disseminate in a transparent manner.
- Consultations in the queue need to be carefully tracked to form raid parties, update the guild on friction (Moloch sightings), and successfully ship.
- Clerics need to efficiently align their work/data so raids/rips don’t slip through the cracks.
- The guild needs an easy and efficient way to share raid/rip updates to other memebers during meetings and asynchonously without requiring a specialized role/access.
- DM is currently not being used by the guild.

## Hypothesis

- The complexity of RaidGuild requires a novel CRM tool to attend to these needs.
- A custom tool will increase the coordination effiency of the guild better than out-of-the-box solutions like Clarity and DeWork, Saimano’s ragehack, etc.
- If we are able to successfully dog food our own CRM, we can extend and apply these learnings to other use cases.
- Basic documentation and training is required to allow guild members to use DM.
- Initial use will provide valuable testing data to inform a DM v2 build.

## Solution

- Compare the current v1.5 DM build to existing tools through rigorous A/B comparative/competitive analysis.
- Elucidate exactly what features DM needs to optimize the Clerical workflow.
- Explicate DM v1.5’s friction points.
- Define parameters for a DM v2 build to ameliorate them.

## Method

- Migrate API to improve usage of core features.
- Use the tool in its current v1.5 state. Compare to other solutions.
- Document current features.
- Conduct educational workshops to encourage usage by Clerics.
- Workshops are recorded and archived for access.
- Craft a testing script based on usage.
- Conduct testing interviews of DM v1.5.
- Analyze/synthesize data into coherent user flows.
- Compile a prioritized backlog of improvements.
- Explicate the goals of a DM v2 build.
- Generate a sitemap and wireframes for the DM v2 build.

### Milestone 1: 8 weeks

- Migrate API to Hasura + Postgres.
- Migrate data from Mongo to new backend.
- Add additional quality-of-life and optimization features, [including but not limited to those outlined here.](https://hackmd.io/@raidguild/BJgndvpKK)
- Conduct initial discovery heuristics of tool through use.
- Compile previous documentation.
- Supplement documentation to allow for use by other members.
- Design, organize, and conduct educational workshop. Record.

### Milestone 2: 8 weeks

- Craft a script based on the data collected at workshops.
- Conduct interviews with Clerics to reveal/confirm friction points.
- Synthesize data into a friction sitemap.
- Define user flows.
- Extract a prioritized backlog of tasks.
- Explicate the goals of the v2 build.
- Generate a sitemap & lo-fi wireframes for the v2 build.

## Raid Party

scottrepreneur#8411
jonathanp#9885
earth2travis#6969
TravisWyche#2116

### Budget
$22k for the team

- 1.8k for jp for v1.5 bounties reimbursement
   - These were paid out of pocket as part of the Season 4 cohort
- 4k for dev (50% RAID)
- 16k for documentation, training, testing, initial design (30% RAID)
    (14.8k Stable/ETH / 8k (in) RAID)

**Comment by earth2travis** [comment]
Received 14,800 WXDAI from proposal [385](https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/385) on November 09.

**Comment by earth2travis** [comment]
Submitted proposal [390](https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/390) for 8,000 (in) RAID on December 1.

**Comment by plor** [comment]
Could this be updated with final links and updates to what was completed?

**Comment by plor** [comment]
https://hackmd.io/@raidguild/DM-backlog
