### ISSUE TITLE
RIP#112 - HireUs UX/UI Update

### ISSUE THREAD

**Issue by IanBoucherTru** [raid-guild/RIPs#112]
# Project Idea
HireUs UX/UI Update

### Project Submitted By

@V4n @sasquatch

## Summary

Improve lead generation funnel for prospective clients, either through submitting a consultation or requesting more information. Open the Raid Guild bank so that consultation fee's can be taken on any chain.
+ Re-Design of the HireUs Page (mirroring new SEO-Rodeo Design Scheme)
+ New Copy for smoothing the funnel, directing prospective clients to submit for more information or submit a new consultation
+ New form for prospective clients that aren't ready to submit a consultation
+ Update the Smart Contracts for accepting funds to include mainnet (+ polygon, arbitrum?) 

Option: to give preferred pricing for funding the consultation with $RAID or for holding >5k $RAID
+ include links to purchase $RAID
(wen $RAID on Mainnet?)

## Why should we build this?

Because we should make it as easy as possible for people to give us money. Make the RG Client funnel frictionless

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Design
- Content
- FrontEnd
- Smart Contracts

## Cost (in USD)

\$1,000 (pending Smart Contact scope)

**Comment by plor** [comment]
I don't think this has moved in a while. I'm going to leave it, but if it is no longer relevant go ahead and close.

**Comment by boucherbox** [comment]
closed as lost, need to revisit following TW's Brand stewardship
