### ISSUE TITLE
RIP: SEO RODEO

### ISSUE THREAD

**Issue by degeneroach** [raid-guild/RIPs#113]
# Project Idea

**Clarity Overview Link:**
https://app.clarity.so/raid-guild/project/52

**Clarity Project Details:**
https://app.clarity.so/raid-guild/work/RAID-60

**SEO Rodeo Links:**
https://app.clarity.so/raid-guild/notes/a07c4255-f71e-4ed5-9222-933c99015ea7

### Project Submitted By

@degeneroach 

## Summary

Currently, [raidguild.org](https://raidguild.org/), a one-page, landing page has an overwhelming amount of DR (Domain Rank). We believe that if we turn [raidguild.org](https://raidguild.org/) into a multi-page website that contains the correct keywords, sales copy, & social proof we can capture more leads into our client consultation queue.
Let's continue building the main Raidguild Nextjs site (Aka "the Dot Org") https://github.com/raid-guild/dot-org-v2 to improve discoverability, contributor onboarding, and client capture.

## Why should we build this?

This is a breakdown of why you believe the Guild should spend resources to build this idea. Does it create revenue? Does it benefit the greater Eth ecosystem? Does it save humanity?

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed
Front-End Build: $1500 ( @0xhanvalen)
Design: $1500 (@degeneroach )
Copy w/ Keyword Optimization: $1500 (@v4n and @stardev)

## Cost (in USD)

$4500

**Comment by bitbeckers** [comment]
If the DR is the key metric and tweaking that should capture more leads: what are the metrics that would make this RIP a success?

**Comment by 0xhanvalen** [comment]
> 

DR is not the key metric, we already have a great DR. The goal now is to use that DR to capture traffic from more relevant keywords a buyer might be searching

**Comment by plor** [comment]
I think this proposal is for this https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/419
