### ISSUE TITLE
0xmaker (scottrepreneur)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#115]
### Championee

0xmaker

### Champion

scottrepreneur

## Summary of work to date

Done some hackathoning and cutting teeth on season 5 projects.

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[link to the staking transaction here](https://gnosisscan.io/tx/0xf66e046013830c68bf6f6ab226b1fac987bdb43c0e834c7e5ea97ebacfef7e34)

## Anything else you'd like to add?

LFTG

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
Eligible for membership on December 30, 2022 until February 28, 2023

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/404

**Comment by ECWireless** [comment]
Closing since this is over a year old
