### ISSUE TITLE
mr_bluesky (bitbeckers)

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#116]
### Championee

mr_bluesky

### Champion

bitbeckers

## Summary of work to date

We've worked together on the Hypercert Raid for Protocol Labs. As a party member we've had a joyful and constructive cooperation where we are able to communicate clearly and deliver what is promised. Mr_bluesky has engineering experience in 'fiat' environments and that shows in the way he codes and sets up test suites.

For additional feedback as a party member, feel free to reach out to either Jip or DAO_Jones

### Applicant source

 - [X] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

https://blockscout.com/xdai/mainnet/tx/0x0ab33103d3474b5ff734574618384406a64b2b501cec5c3df9ab2168aa93c694

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/399

**Comment by plor** [comment]
@bitbeckers you should request your stake + reward back soon. We added a window for these to be requested and this one isn't grandfathered in, so technically you could be ineligible depending on how close we follow the rules.

**Comment by plor** [comment]
https://blockscout.com/poa/xdai/tx/0x4cf3323bacd5e7bb2790d35bae11f82735ef1467ee60b7b8e7cdda4ba9c74c80 executed!
