### ISSUE TITLE
benedictvs (scottrepreneur)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#118]
### Championee

benedictvs

### Champion

scottrepreneur

## Summary of work to date

Been clutch in organizing proposals throughout Season 5 and beyond. Great vision for implementation and a burning desire for DIDs. Working on Rite of Moloch RIP and Healers Guild summoning.

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

https://gnosisscan.io/tx/0xc5dd486a6e72bd4d4d3ef2854326a00d56ee81aac70d07737c3ea4ec2500216d

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/417

**Comment by plor** [comment]
https://blockscout.com/xdai/mainnet/tx/0x769282078803cd2196419baa3ec26f40fe7bfcd948281508c4ad25313eee0494

**Comment by ECWireless** [comment]
Closing since this is over a year old
