### ISSUE TITLE
Consolidate and optimize knowledge in Charmverse

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#119]
### Project Submitted By

scottrepreneur, benedictvs

## Summary

We've had a few small attempts to consolidate knowledge but no meaningful solutions for driving process change in that. We want to incorporate the learning from this as we transition away from public collaborative docs. There are other tools on the market but there are markdown based and could be imported to other tools with minimal switching costs.

The cost here is for building & adapting the content and hierarchy with buy-in from members that makes sense in our current flows. The technical import cost is fairly minimal. The structure would largely be available for bringing to new tools also.

## Why should we build this?

We need better ways to surface shared knowledge that hasn't been christened in the handbook. We move too fast and the handbook can't keep up with our operational capacity.

## Anything else you'd like to add?

Process

1. Set up Charmverse workspace and configuration for the needs of Raid Guild
3. Import to Charmverse
4. Structuring the information and validating imported data
5. Compiling an onboarding document and/ or educational material for getting started with Charmverse
6. Setup role-driven permissions for cohort
7. Explore opportunities for the guild to make connections via charmverse

Costs

Charmverse is free while in beta, Summer 2023. This group will work with Charmverse to ensure DAO-friendly pricing options, given it is still meeting our needs at that time.

## Raid Party Skills Needed

- Healer
- Scribe
- Bard

## Cost (in USD)

1k Dai

**Comment by plor** [comment]
This was part of winter brigade, so streamlined RIP process. It has been paid out and should be considered complete.
