### ISSUE TITLE
RIP 122: Portfolio - Raids Archeology

### ISSUE THREAD

**Issue by BorrowLucid** [raid-guild/RIPs#122]
# Project Idea

The [SEO Rodeo RIP](https://github.com/raid-guild/RIPs/issues/113) has a Portfolio with authoring! (woohoo) To get that Portfolio full of awesome Raids, some major data archeology needs to happen.

This RIP includes all that archeology, as well as entering the information uncovered into the new website.

### Project Submitted By

BorrowLucid

## Summary

This RIP includes collecting data to feature 12 of the following Raids. Priority will be given to Raids with the easiest access to information. Preference will also be given to those requested to be featured by Raiders and to Raids that demonstrate types of projects that Raiders prefer to work on. The most current [information about Raiders' Raid preferences](https://hackmd.io/s0g8Oa38SQCg4_16UR_CVA) was collected by BorrowLucid, November-December, 2022.

	Aavegotchi
	Boardroom
	Bufficorn Buidl Brigade
	Destake
	GeoWeb
	Gitcoin (Moloch Comic)
	Gnosis Guild App
	Liquity
	Metl
	Paladin
	Perfect Pool
	Potion DAO
	xDai Omni Bridge
	wPokt app
	Song A DAO
	Opolis
	NFTX
	Moloch DAO
	Govrn
	Nifty Chess
	Maple Finance
	SW Capital
	StakeOnMe
	Stake DAO
	Red Pill NFT Claim Mech/ Website build
	SongADay (I, II, III)
	NiftyApes
	TrashDAO
	MetaStreet

Information being extracted about Raids will be focused on a template provided by the SEO Rodeo team, which includes the following information, of which copy editing will be applied to present the Raid in it's best light:

	Project Name

	Website URL
	Github URL (optional, can also be etherscan)
	Project Description

	Image (square pls)

	Applicable Services (csv tags)

	Contributors (array of Role/Raider Name pairs)

	The Challenge

	Our Approach

	Results
    
The process this RIP will follow includes the following.

    1. Review of Raid documentation to prioritize them internally.
    2. Optimize order of completion of portfolio data collection according to metrics (audience, presumed client preferences, internal Raid preferences).
    3. Complete first print.
    4. Retrospective with feedback from EthDenver.
    5. Complete second sprint.
    6. Overall retrospective

## Why should we build this?

Raid Guild is hacking at EthDenver 2023. Raiders tend to win prizes. This is a perfect time to talk to potential clients, who noticed the successes of Raiders in the hackathon.

Raid Guild has also been entered into the first year of the American Metaverse Awards. Getting shortlisted is highly likely. The winner is announced at an IRL event at the end of March, in Miami. Attendees will be startups and VCs interested in building in the Metaverse. This is a perfect time to talk to potential clients.

Potential clients who don't already know Raid Guild will want to see examples of previous work. EthDenver and American Metaverse Awards are useful deadlines to have something polished and ready for, but the portfolio will be useful for many months.

## Anything else you'd like to add?

As part of retrospectives for Raids, Clerics are encouraged to enter information about the Raid into the Portfolio authoring form on the website. Clerics are also encouraged to ask for help with this if needed. It's better to ask for help, then to skip it.

## Raid Party Skills Needed

Scribes:
benedictvs
ApereionCreations
BorrowLucid

## Cost (in USD)

$1800

### Phase 1 (for EthDenver, March 2-5, 2023)

6 Raids at $150 each

### Phase 2 (for American Metaverse Awards, March 29-30, 2023)

6 Raids at $150 each

## ROI

Let's see how many new clients are coming through the hire us channel in mid-March and mid-April. Key word here is *new*! The portfolio is for new friends of Raid Guild, not old clients who already know what the Guild can do.

**Comment by BorrowLucid** [comment]
- [RIP multisig](https://app.safe.global/gno:0x5f8F6c06D6b38Aaa55aC0d8262a05dE55713b080/home?showCreationModal=true)
- [Smart Invoice escrow](https://app.smartinvoice.xyz/invoice/0x64/0xd8aa64b7d581c33887371705bb81cf85b8429202)

**Comment by BorrowLucid** [comment]
- [RIP multisig](https://app.safe.global/gno:0x5f8F6c06D6b38Aaa55aC0d8262a05dE55713b080/home?showCreationModal=true) 
- [Smart Invoice Escrow](https://app.smartinvoice.xyz/invoice/0x64/0xa504afc23ebc4a2e97df754913a2e06a2c288511)

**Comment by plor** [comment]
Feel free to close this. I'll just leave it here if there are any notes to add on the completion of this RIP.

**Comment by BorrowLucid** [comment]
It's all in here: https://app.charmverse.io/raid-guild/page-3622683448182513
And thanks to Scott, it's all up here: https://www.raidguild.org/portfolio
