### ISSUE TITLE
Dungeon Master packages and smart escrow migration

### ISSUE THREAD

**Issue by kon-rad** [raid-guild/RIPs#127]
# Project Idea

Extract common utilities to separate libraries inside of Dungeon Master and import them inside other apps. In part two, migrate smart escrow to be inside Dungeon Master.

### Project Submitted By

scottrepreneur#8411
0xmaker.eth#7252

## Summary

*Part I*
extract all utils, hooks out of DM, into a new utils package in `dungeon-master-v2/libs`
  utils will have the following sub packages: `graphql, hooks, utils, types, custom-tsconfig, and custom-eslint`

- this is done with nx to manage monorepo 
- can be imported by other apps, e.g. cleric calculator
- makes hooks accessible to any app that needs it
- update DM to use this package
  - includes graphql, hooks, types, utils, some assets
- Update dot-org with hooks from new library
- add ts-docs to components and functions on the above packages and design system

*Part II*
migrate smart escrow to be pages inside Dungeon Master

- use shared library utils, and Design System components
- list view is not needed
- consists of 2 pages
- update the state management to use hooks pattern
- use existing DM wagmi wallet connection and create Client role for authentication
- archive current smart escrow app

## Why should we build this?

This is a good idea because it allows for reusability of code across repositories, such that functionality doesn't need to be reinvented. Keeping things D.R.Y. and to have consistency in functions and configs across multiple applications.
Migrating smart escrow into Dungeon Master for a closer integration, helps refresh the app, integrate with Design System components.

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Warrior (frontend) - 0xmaker.eth#7252

## Cost (in USD)

$4,500

**Comment by plor** [comment]
Just wanted to note this will seek retroactive funding per discussion on discord.

**Comment by kon-rad** [comment]
Shipped

https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposals/13

**Comment by plor** [comment]
> Shipped
> 
> https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposals/13

The point of the documentation column is that a markdown file is created in this repo so it is clear what was built for the guild and why. Shipping a RIP then requires delivering the code as well as documenting it.
