### ISSUE TITLE
RIP: Smart Escrow / Dungeon Master Update

### ISSUE THREAD

**Issue by geovgy** [raid-guild/RIPs#130]
# Project Idea
Update the Smart Escrow components in Dungeon Master to fit with the new Smart Invoice factory contract.

### Project Submitted By

georgeh#4059

## Summary

There are two parts that will done:
1. Smart Contract
2. Frontend

Timeline: 3-5 weeks

### Smart Contract
- Eliminate the Factory Wrapper contract
- Absorb Invoice Wrapper into SmartInvoiceEscrow for new invoice type
    - Duplicate SmartInvoiceEscrow
        - **Stretch goal:** Update milestone release from fixed sequential order to arbitrary order
    - Add split factor and DAO provider
        - **Stretch goal:** Allow split to N providers
    - Implement disperse function in contract
    - Set implementation in SmartInvoiceFactory

### Frontend
- Revise invoice creation
    - Change [EscrowConfirmation](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/components/EscrowConfirmation.jsx) component to reflect smart contract update
- Revise [invoice utils](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/utils/invoice.js)
- Revise or remove [InvoiceMetaDetails](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/components/InvoiceMetaDetails.jsx) component
- Update or trim [InvoiceButtonManager](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/components/InvoiceButtonManager.jsx) component
    - Change lines including raidParty and wrapped invoice
        - No longer need withdraw from wrapped invoice contract
- Revise or remove [WithdrawWrappedBalance](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/components/WithdrawWrappedBalance.jsx) component
- Revise [LockFunds](https://github.com/raid-guild/smart-escrow-nextjs/blob/develop/components/LockFunds.jsx) component or its implementation
    - Ensure wrappedInvoice is not needed for provider to lock

## Why should we build this?

Smart Invoice has made breaking changes to the escrow and factory contracts that requires major revisions to the wrapper contracts used by Smart Escrow.

Oddly enough, it will be quicker and easier to retire the wrappers and incorporate its split properties into the escrow contract as its own invoice type. Therefore, Smart Escrow will just be using the Smart Invoice protocol directly.

This will lead to less maintenance as the wrapper contracts will be archived and Smart Escrow will only need to maintain its frontend repo.

## Anything else you'd like to add?

This is a subsequent RIP to be implemented and accomplished after the DM Packages and Smart Escrow Migration RIP #127.

Since the smart contract will be under Smart Invoice, Raid Guild will be requested to fund only 50% of the cost related to smart contract work.

## Raid Party Skills Needed

- Wizard (georgeh#4059)
- Warrior (0xmaker.eth#7252)

## Deliverables
- [x] Smart contract of new invoice type with splitter
- [x] Deploy and set implementation in `SmartInvoiceFactory` on Gnosis Chain
- [ ] Update dungeon master / smart escrow frontend

## Cost (in USD)

| Milestone       | Amount     |
| --------------- | ---------- |
| Smart Contract* | $2000 |
| Frontend        | $1500 |
| **Total**       | **$3500** |

The total cost for each organization will be the following:
- Raid Guild: $2500
- Smart Invoice: $1000

**The compensation for smart contract work will be split 50/50 between Raid Guild and Smart Invoice. This does not apply to the frontend work. The compensation for frontend work on smart escrow will be covered 100% by Raid Guild since its purely for internal use.*

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/427

**Comment by geovgy** [comment]
Marked completion on the smart contract related tasks. The new invoice type (referred as `split-escrow`), deployment and implementation on Gnosis Chain are included in the merged [PR](https://github.com/SmartInvoiceXYZ/smart-invoice/pull/125) above.

**Comment by kon-rad** [comment]
Shipped

**Comment by kon-rad** [comment]
Frontend Invoice link https://app.smartinvoice.xyz/invoice/0x64/0x4a98aa92b8463817743628d7a24b7859f91e3693/

**Comment by plor** [comment]
This is the documentation I'm talking about: https://github.com/raid-guild/RIPs/tree/master/PROPOSALS
