### ISSUE TITLE
Preparing RoM for Season VI

### ISSUE THREAD

**Issue by benedictvscriticus** [raid-guild/RIPs#133]
# RIP: RoM 4 Season VI

### Project Submitted By @benedictvscriticus 

This RIP provides the mandate to foster adoption, remedy bugs and UI/UX flaws of the existing application and enter into funding relationships with external parties.

## Objective

We anticipate Rite of Moloch gaining traction as a tool within Raid Guild during the next cohort season, but also external partnerships with DAO infrastructure providers have gained velocity. Although Raid Guild may not be ready to engage into a venture DAO setup of sorts, we believe it should invest in furthering its brand and improve its custom-built tooling. Hence, we propose an improvement RIP to fund thorough pre-production-grade testing, document all flows in a detailed manner for seamless onboarding, and market Raid Guild in an application-based manner.

## Deliverables

We foresee five types of deliverables, improving the frontend, fortifying the technical architecture, role-specific documentation and onboarding support, and engaging in marketing-type partnership engagements. These are described as follows:

- testing of backend and smart contracts for edge cases
- remedying frontend bugs
- fixing misaligned components on the frontend
- improve error reporting
- produce an onboarding video for the next cohort and cohort managers
- role-based documentation including screenshots
- partnership scoping, such as with JokeDAO and Charmverse
- one (1) grant applications
- set-up marketing channels and initiate posting
    - one (1) long-form blog posts
    - three (3) social media posts
    - up to two (2) appearances in podcasts, Twitter Spaces, or similar

## Team

- Full-stack developer: @hking2
- Testing: @bitbeckers 
- Technical Project Management & Partnerships: @benedictvscriticus 

## Scope

Some steps for improving RoM have already been taken, for example was RoM deployed to a custom domain, a walkthrough has been recorded, and marketing engagements with Charmverse were planned. Thus, this proposal only formalises work undertaken and secures a sustainable operation of Rite of Moloch as part of Raid Guilds core infrastructure. It aims to achieve an increase in app users and further Raid Guilds market traction by

- funding the exploration of integration potentials for RoM with DAO tooling providers, such as JokeDAO, DAOHaus, and Charmverse
- engage in use case-based marketing endeavours for Raid Guild
- polish the application, including bug fixes, minor UI/UX improvements, and adding descriptions
- reviewing and testing the code for edge cases
- writing and publishing documentation

## Budget:

72 hours of work over the course of a two months period at an hourly rate of USD 75 makes the request grand total USD 5,400.

## Process

The RIP is scheduled to be completed after two months and is expected to report on a weekly basis to Raid Guild. The team has a total of 95 hours at its discretion, thus, is expected to dedicate an average of approximately 48 hours per month to the project.

Billing within the team is done by internal time recording and funds are released using the existing minion safe setup.

**Comment by St4rgarden** [comment]
Super excited to see this in prod.  Even the simple prototype was super effective for Season V cohort.

My only concern with this is that:

-It remains owned by Raid Guild
OR
-It remains as a free public good
OR
-Everyone that participated in creating value for this project is included in any venture related to RoM

**Comment by benedictvscriticus** [comment]
@St4rgarden, despite the current focus on ironing out the deleted subgraph branch and making it a consistent mono-repository project, these questions should not remain unaddressed. As you have originally created the first version, I invite you to join the conversation to find the best solution for all stakeholders and the product.

**Comment by benedictvscriticus** [comment]
# Retrospective

## Sprint 1

- [X] remedying frontend bugs
- [X] fixing misaligned components on the frontend
- [X] role-based documentation including screenshots
- [X] partnership scoping, because we scoped it with Metagame
- [X] one (1) grant applications -> Orange DAO
- [X] appearances on Charmverse Twitter space
- [X] set-up marketing channels -> twitter

## Sprint 2

- [X] produce an onboarding video for the next cohort and cohort managers
- [X] https://app.arcade.software/share/ZMqXcAMVGCFmp4wrTJH3
- [X] improve error reporting
- [X] and initiate posting one (1) long-form blog posts 
- [X] three (3) social media posts
    - [X] 1/3 (https://twitter.com/riteofmoloch/status/1667626957226356738?s=20)

## Sprint 3

- [X] improve error reporting
- [X]and initiate posting one (1) long-form blog posts
    - [X] https://mirror.xyz/0x81865ebC7694Dfba6608F6503BBA50Abb04644b4/TOt8NaKla9EuXB9P_xIk2GyWxkGdltSomue6zL5jFYk
- [X] two more social media posts
    - [X] https://twitter.com/riteofmoloch/status/1679591440400146434?s=20
    - [X] https://twitter.com/riteofmoloch/status/1674904144405045251?s=20
- [X] testing of backend and smart contracts for edge cases
- [X] Fixing fuckups season 6
    - [X] Gnosis chain chain image Rainbowki
    - [X] BROKEN: Cannot deploy as shaman
    - [X] BROKEN: Join got NO cohort address
    - [X] Refresh Graph query 

## Payout

https://app.smartinvoice.xyz/invoice/0x64/0x32d310a57851e9945689e236bf4435aa7c0ea972/
