### ISSUE TITLE
Spring Cleaning

### ISSUE THREAD

**Issue by plor** [raid-guild/RIPs#134]
# Project Idea

For the Spring Brigade we will undertake a spring cleaning of DAO resources. This is primarily focused on discord channel organization, but may encompass other tasks that should be periodically undertaken for the health of the Guild.

### Project Submitted By

plor

### Purpose

We will meet to discuss ideas on what changes should be made to discord to make it easier to navigate and use. Once we have a clear plan of action, run it by people to make sure there aren't too many concerns. Then make the changes.

### Background

There have been shifts in the discord channels over time, with occasional cleanups by the miniadmins. We accrue channels over time and they go stagnant as time passes. Having clear plans that are documented will allow for a bit more continuity. This can be re-run as part of future brigades and have a jumping off point.

Understanding why channels exist and why the don't need to continue is a great service for tracking the changing landscape over time. By establishing the process and documenting a snapshot of discord it will make it easier to perform this function in the future. Perhaps even in an ad hoc manner by individual contributors to "take out the trash".

### Methodology

 - Snapshot: Create list of current channels/categories
 - Discovery: Determine purpose of channel and future prospects
 - Rule: Discuss each one and make recommendation for change
 - Act: Send channels to valhalla or ask miniadmin to make change

### Cost

An initial budget of $750 is set to perform this work. This is up to debate but just intended to set a starting point.

## Why should we build this?

This has previously been done as a one-off task by those with privileges to do so. Documenting what actions and why they are undertaken will be a better solution to make this a regular task that maintains consistency over time.

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Organization

## Deadline

May 28 (Final steps can be taken during the weekend to avoid disruption).

## Cost (in USD)

\$750

**Comment by plor** [comment]
It was also brought up that @manolingam should be consulted for backups of all channels moved to valhalla to make sure history is not lost.

**Comment by ECWireless** [comment]
@plor what would count as good success criteria here? For instance, if even after going through the entire methodology, only 1 channel gets sent to valhalla, is this project still considered successful? Maybe we ask the guild to rate the cleanup effort at the end?

Also, is it possible to list concrete deliverables? For instance, will documentation from going through the methodology be included in the retro at the end (like, I think people would be curious how many channels we had at the start vs the end)? I think another good deliverable would be documenting where our valhalla archive actually is (and perhaps making sure there's no risk of that archive being lost).

**Comment by plor** [comment]
@ECWireless I think success here is that all 4 stages are complete. I could see the discussion becoming contentious and not being able to come to consensus in a way that it doesn't deliver. I would be against a numeric goal, since that would necessarily influence the decision making, likely negatively. A qualitative judgement based on members feeling better about the discord after than before would be fine, though I think that might be overkill here.

As for diving into the valhalla archive process, that is something that is important. But I'd like to keep it separate as that is a quite different task than the organization of channels. Hopefully it can come out of this by way of forcing the issue, but I don't feel comfortable including it as an explicit deliverable.

**Comment by ECWireless** [comment]
@plor ya, I get that trying to get ether quantitative or qualitative feedback could be cumbersome and noisy... maybe it should simply be on the Brigade Committee to check the retro against work that was done, which would lead to their own assessment in the overall Brigade Retro

**Comment by plor** [comment]
@ECWireless yeah, we could put weights on the 4 phases as well. That way the committee has something to base the completion against. I'd say something like (10%, 25%, 40%, 25%) if I had to ballpark it.

**Comment by ECWireless** [comment]
@plor ah, nice, weighted assessments on deliverables is a great idea. I feel like it should be done for all projects

**Comment by plor** [comment]
Updated to set May 28 as deadline. Retro notes may be worked on after delivery.

**Comment by plor** [comment]
Lettucemeet for those interested https://lettucemeet.com/l/AbXaL

**Comment by plor** [comment]
# Retro Thoughts

## Good things learned

There wasn't as much change needed as we might have first thought. We also learned a lot about the discord setup from going through this exercise. One valuable piece of information worth highlighting is that the app to view the archived channels exists at https://the-valhalla.vercel.app/ .

In addition to the process of documenting our decisions we learned that the #memes channel is more loved that we expected. After moving this to valhalla there was overwhelming support for returning the memes channel from whence it came.

## Bad things learned

This is a long process that unfortunately needs to be undertaken at a regular cadence because the number of channels continuously grows and keeping discord slim is a difficult task. Hopefully the process will help to inform future iterations of this process in order that they can more quickly achieve the results we had.

There were some hidden/tribal knowledge that we weren't able to uncover with the history we had. We tried to follow the parable of Chesterton's Fence and not destroy what we did not understand, but unfortunately we may have taken action on channels that were fulfilling an important purpose that was lost on us. Documenting such information and having it surface at the right time is difficult, but processes like exporting valhalla and other previous decisions should be more clear to a group like the one assembled.

Lastly, there were many camp/raid/rip channels that should not have needed this process to take place in order to be cleaned up. The owner of those efforts should be more conscientious about cleanup of these artifacts when closing out the work.

## Current state

The valhalla was exported to make room for more channels, and the changes made to archive or change channels were made. Any additional feedback should be directed to this team, but we consider the effort complete.

## Next steps

- Move https://the-valhalla.vercel.app/ to a subdomain on raidguild.org
- Document the valhalla export so future cleanups can execute it
- Address the guild.xyz questions that were raised and whether the barrier there is beneficial
- Look into restructuring internal services into DAO Unit structure to make it more clear

## Summary

This was hopefully a valuable effort, the team who performed it would welcome feedback. More importantly it is a process that can hopefully be continually followed by using https://app.charmverse.io/raid-guild/page-007690548739854197 as a starting point for what has been done and what cleanup might need to occur going forward.

**Comment by plor** [comment]
@ECWireless Another note that would be useful in the retrospective is that Jaqi brought up in her presentation that people looking for quick UX testing should go to wine-cellar. We removed this, but I thought it would be useful to note this.
