### ISSUE TITLE
Business Model workshops to refine Raid Guild’s positioning

### ISSUE THREAD

**Issue by benedictvscriticus** [raid-guild/RIPs#135]
# Project Update RIP [#135](https://github.com/raid-guild/RIPs/issues/135) and [#139](https://github.com/raid-guild/RIPs/issues/139)

Lately, it's become apparent that Guilders lack effective resources and frameworks for describing (or shilling) Raid Guild to others, especially potential new clients. Inbound leads have been few & far between, and Guilders have begun to do more outbound business development to secure new clients. 

Agreement was reached that Raid Guild must enhance marketing positioning and unify messaging that effectively expresses Raid Guild's unique value proposition(s). This needs to be agile and efficient; marketing initiatives that are research heavy and produce lengthy reports with little actionable items are seen as not helpful. 

We propose a the production of two decks: a BD deck meant to be distributed/presented to potential clients, and an EPK more for general outreach. The process to architect both decks is near identical, and below we outline a flow to do just that.

### Project Submitted By

@st4rgarden, @benedictvscriticus, @joshsdoug

### Workshop (90mins): Raid Guilds business model

- Utilizing a [business model canvas](https://en.wikipedia.org/wiki/Business_Model_Canvas) (BMC) to pinpoint RaidGuild's competitive positioning
    - identify key partners, key activities and value proposition of Raid Guild
    - refine customer segments and channels that are the most promising
    - define our customer relationships
    - excavate existing and desirable revenue streams to offset operating costs

### Public Working Session (90mins): Refinement

To be mindful of participant's time while maintaining transparency, we will schedule a public working session to refine the inputs from the Workshop. During this session, we will organize the Workshop finidngs into a formal BMC. We will also begin work on RIP Deliverables.

Anyone interested in participating is welcome to join, however, active conversations are not necessarily required to be maintained by attendees.

- review of BMC inputs
- contextualisation of outputs
- voting on created unique selling points (USPs)
- refinement and roadmapping of actionable tasks

### Presentation

- presentation of the results in the larger group
- design of pitch material for concrete marketing efforts identified in the workshops
- review & retrospective
- communication of work done in media engagements

### Deliverables

- one workshop totalling 90 hours in duration
    - with a prepared design thinking board
    - contextualisation of the status quo of Raid Guild
- pitch deck
- EPK
- retrospective and presentation of results in a larger group

### Objectives and Key Results (OKRs)

* Deck utilization
    * Objective: Guilders should use these materials, and potential clients/partners should see them
    * Key Result:
        * Pitch Deck: 6 uses in 3 months
        * EPK: 6 uses in 3 months
* New clients/partners
    * Objective: These materials should successfully be used in the shilling/conversational process
    * Key Result:
        * Pitch Deck: 2 new clients onboarded who were sent/pitched this deck
        * EPK: 1 new partner who was sent/pitched this deck
* New dealflow
    * Objective: The pitch deck should have some ROI; spoils from new clients who saw the document should eventually dramatically outweigh the cost
    * Key result:
        * 1,450 xDAI in Spoils in next three months (RIP Budget)
            
## Why should we build this?

Guild members need to have the resources and frameworks in how to effectively communicate the work and positioning of RaidGuild. This exercise is light weight and likely produces actionable items for focused marketing initiatives, while producing streamlined marketing messaging for Hunters.

## Anything else you'd like to add?

The change log and comments can be found [here](https://hackmd.io/H-HPBTkCTwia7QGDBFUz5w?both).

## Raid Party Skills Needed

- Archeologist
- Archer

## Cost (in USD)

Given an estimate of ten (10) hours to prepare and hold the workshops, to which sixteen (16) hours are added to produce the promised material, as well as three (3) hours for a designer to polish the deliverables, we would like to request one thousand fourhundred fifty (1,450) US Dollars.

---

### 1,450 USD

---
---

**Comment by St4rgarden** [comment]
Looks pretty good to me.

I will definitely attend this.

**Comment by ECWireless** [comment]
@benedictvscriticus damn, this looks like a lot of work ("This exercise is light weight" 😅)! Really excited about this project--I can see this going beyond your expected hours, though, and would pad the cost $100-200 more.

Also, how would you determine the success of a project like this? I think something like tracking the media engagement by views/clicks, or doing a 1-2 month follow-up on the business model canvas' usefulness, are two ways you could go about it

**Comment by benedictvscriticus** [comment]
> @benedictvscriticus damn, this looks like a lot of work ("This exercise is light weight" 😅)! Really excited about this project--I can see this going beyond your expected hours, though, and would pad the cost $100-200 more.
> 
> Also, how would you determine the success of a project like this? I think something like tracking the media engagement by views/clicks, or doing a 1-2 month follow-up on the business model canvas' usefulness, are two ways you could go about it

Thank you for this feedback. Luckily, @joshsdoug0 reached out because he is interested to help. We certainly appreciate the padding and your recommended success metrics sound reasonable and actionable. I will be meeting with @joshsdoug0 on Friday, prior to our SG weekly. We then further refine the proposal and have it ready for execution.

**Comment by benedictvscriticus** [comment]
As requested by @ECWireless, I included an itemised list of sections that are included in a pitch deck:

- Problem statement
- Our USP/ solution
- Portfolio
- Products
- Guild culture
- Positioning
- Summary

It specifically is distinct from an electronic press kit (EPK) through its use. An EPK is for cold leads and consists of a nucleus version of a pitch deck, whereas, a pitch deck should be a slide deck master for a living document used by hunters for warm leads. Thus, the EPK is something any raider can forward to a cold lead without any changes and pitch decks should be tailored and amended to the concrete sales context.

**Comment by benedictvscriticus** [comment]
# A Brief Retrospective

## Lessons Learned

Conducting a business model canvas workshop was first met with some scepticism, as the ultimate and tangible deliverable of such a workshop was not as clear as desired and the effort got conflated with KPI-driven marketing. After thorough discussions and proper scoping, we finally started modelling. It was great fun.

### Highlights

Scepticism during the brigade preparations ameliorated into active participation by over 20 Raiders in the workshop. We generated an immense amount of data that was condensed into an authoritative slide deck named 'BMC'. It was a great opportunity to work with long-standing Raid Guild members (shoutout to @joshsdoug) and opened new perspectives on long completed Raids. The knowledge we surfaced enabled us to deliver a consistent pitch deck for use by many Raid Parties.

### Low-Lights

Scheduling and task assignment could be improved next time such initiative is executed. Over the course of completing the work streams we have discovered that there is a severe shortage of Archers within the Guild. Furthermore, dependencies between multiple initiatives have caused bottlenecks and scope changes. It is unfortunate that other Brigade initiatives were unable to consume our output due to holidays, varying professional obligations, and external contingencies. Lastly, we could not verify the delivery of the EPK at the time of writing this retrospective.

## Status

One workshop was held that drew Guild-wide participation. The results were reviewed and discussed in a public working session. The BMC was transposed into a slide deck, which forms the basis of a draft for a pitch deck on Google Slides. The Google Slides-based pitch deck was transformed into Figma assets and is now available to all Raiders as consistent work deck.

## Next steps

- add more detail to technologies used in the case studies
- customise for personal Raid Party
- track usage and follow up on results next quarter
- ensure the fulfilment of OKRs

## Summary

It was a fun and fulfilling experience that turned out to be more complex than expected. We uncovered interesting sales angles and new Molochs, which made all parties involved bond and share their perspectives. Controversial and widely accepted arguments were heard, but a state of the art analysis delivered. We now can go out to Raid with a shared voice. We will be back to check in whether we were heard.

**Comment by St4rgarden** [comment]
# EPK Draft #1

Here's the first draft of the [EPK](https://docs.google.com/presentation/d/1NGdl-cZCKG1KwvnVnGmWSFMn5rRMwOWmsmyfXPZSFp0/edit#slide=id.g20a60326039_0_285)

This is just designed to give people the very most basic information about Raid Guild; and to get the saliva flowing a little bit, to get their imagination churning about us; and building Web3 products in general.

**Comment by benedictvscriticus** [comment]
After three months, the retrospective on the OKRs yields disappointing results. While initial interest was large and even throughout the retrospective period members signalled interest in using it, the pitch deck did not actually lead to a deal closed. This can be attributed to the overall state of the market, but may also point to information asymmetries within the guild.

It is important to note, however, that the pitch deck template has proven immensely valuable in the communication with existing clients. Namely, the pitch deck was used to facilitate and document delivery sessions with Lobby3 and was the basis for ROM's earliest marketing engagements.

More work remains to be done to improve knowledge and resource flows within the guild, as well as to improve the utility of brand and marketing assets.

**Comment by ECWireless** [comment]
@benedictvscriticus thanks for writing up the follow-up! Because of Discord feedback (cc @plor ), are you able to lay out results in the same format as OKRs listed above? For instance:

### Deck utilization
- Objective: Guilders should use these materials, and potential clients/partners should see them
- Key Result:
    - Pitch Deck Goal: 6 uses in 3 months
    - EPK Goal: 6 uses in 3 months
    - Pitch Deck Result: ______
    - EPK Result: ____
...

- Also, I'm curious your take on why the Pitch Deck hasn't been used more, other than just a slow market. My own intuition is that there either aren't enough hunters or clerics to make use of them, or these hunters / clerics already have their own methods and don't really need a Pitch Deck. I also have a slight feeling some people didn't want to put the effort into tracking down where the Pitch Deck was located.
- Finally, do you think BizDev / Marketing projects are worth pursuing in future Brigades? I know that some people voiced their concern over this at the beginning of the Brigade... My own take is that Brigades should purely stick with dev (and some non-dev) Internal Operations efforts

**Comment by benedictvscriticus** [comment]
# Deck utilization

## Objective: Guilders should use these materials, and potential clients/partners should see them
### Key Result:
#### Pitch Deck Goal: 6 uses in 3 months

The pitch deck template was used three times in client meetings, however, the pitch deck was not used for any warm leads or potential clients.

#### EPK Goal: 6 uses in 3 months

The EPK was not added to the website and the status was not reported by @St4rgarden. Hence, we must labelled it as unused in the first three months.

Pitch Deck Result: underdelivered
EPK Result: undelivered

RaidGuild recently has generated clients primarily of personal connections instead of business development. Like the distribution of raidguild.org email addresses, the distribution of communally owned resources is dysfunctional. Active propagation does not suffice when no continuous ownership over processes is established.

*Finally, do you think BizDev / Marketing projects are worth pursuing in future Brigades?*

I would not categorically dismiss them, as I am not aware that strict KPIs are applied to technical deliverables. Thus, we are not aware whether such initiatives yield worse results than software development brigade contributions. Brigades appear to bring more continuity due to their longer run times than standalone RIPs and I do not feel comfortable to draw final conclusions. Yet, focus on operations should be the main objective of Brigades.
