### ISSUE TITLE
FALL Brigade: Putting the Dev into BizDev (re-proposed)

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#137]
# Project Idea

Host a brainstorming session and deliver a playbook for dev focussed marketing on Raids/Rips/developments.

## Deliverables
- Brainstorm session to gather ideas (facilitated by a marketeer - got a line with a fren)
- Playbook document in handbook and/or Charmverse

### Project Submitted By

bitbeckers

## Summary

To grow and facilate our marketing efforts we could a) use insights and inspiration on how to  work on bizdev with a development focussed DAO and b) structure those insights and inspirations into a 'Raid Playbook' for building Raid Guild presence.

For example:
- Putting RG in the code we deliver (web, evm, bash, whatever)
- Illustrating communications that promotes RG during meetings, talks, etc..
- Checklist with items like "Tweet", "Blogpost", [list of Discord Channels]

## Why should we build this?

One of the strengths of Raid Guild is our capability to build cool shit with a yolo attitude. But we're not strong at marketing our deliverables or achievements. A small step we could take with high impact is marketing Raid Guild while being Raid Guild. 

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Stamina
- Performance
- Investigation

## Cost (in USD)

$750

**Comment by ECWireless** [comment]
Closing due to the age of this RIP proposal
