### ISSUE TITLE
Spring Brigade: Feudal Levy

### ISSUE THREAD

**Issue by psparacino** [raid-guild/RIPs#138]
# Ownership and Contribution Structure  
  
## Summary  
  
The ownership and inactive member discussion has been a topic of much circular debate.

The lack of ownership structure is one of the most cited reasons for lack of greater involvement in guild projects.  This lack of ownership structure also extends to the value held and delivered by inactive members.

Additionally, members often feel invested effort often stagnates and does not lead to real movement.

There is a potential solution where members are awarded shares for raids *or* a minimum contribution of service within a certain time period. If members meet their 'dues' they then receive enough shares to not be diluted.

In this model there are also the added benefits of more activity within the Guild, activating inactive members through contributions of their current skill sets, reward to active Members with the tangible reward of shares, and sense of ownership all of which will lead to more momentum and clients. This will also reduce the outflow of funds on smaller RIPs.

There are *many* details to hashed out in this model. ie.e time period, size of task, % of dilution, incentives etc. While RT and RR are valuable for debating the larger topics, the discussions can often end resolved with too many opinions on the floor.  

This RIP will consist of creating a rough proposal, sourcing feedback from raiders with a private form (and pestering everyone who doesn't answer), 1-1 calls if necessary, and creating a proposal that has a positive chance of passing.

## Deliverable

An on-chain proposal whether to adopt the system that emerges from the brigade.

With this structure in place, discussions about ownership of projects in the Guild have a much higher likelihood of producing tangible results as there will be a precedent of effort invested vs reward.

## Why should we build this?  
  
This proposal does not directly create revenue. However, the ongoing discussions without tangible resolution often preclude forward movement. This proposal will attempt to codify the organizational discussions so that more tangible progress can .
  
## Raid Party Skills Needed  
  
- Raiders
  
## Cost (in USD)  
  
$400... maybe? If the above system is adopted, this small RIP would be an example of the dues paid

**Comment by ECWireless** [comment]
Closing due to the age of this RIP proposal
