### ISSUE TITLE
Spring Brigade: EPK Presentation for non-BizDev

### ISSUE THREAD

**Issue by St4rgarden** [raid-guild/RIPs#139]
# Project Idea
Let's build a press kit inspired presentation to make creating warm leads super easy for non-BizDev Raid Guild Members

### Project Submitted By

st4rgard3n

## Summary

We need a spicy yet neutral presentation kit which can be easily forwarded to any potential clients.  Typically when someone is interested in Raid Guild; a member will just forward the link to Raid Guild's website.  The website is good; but it's not specifically targeted to addressing the value proposition of Raid Guild.  We need a simple press kit presentation that can be easily forwarded by Raid Guild members that conveys our unique value proposition and strengths.

## Why should we build this?

A simple EPK and FAQ companion could increase word of mouth referral conversions; directly leading to higher revenue for Raid Guild.  It's also one of the lowest hanging fruits as it requires very little upfront. 

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Design
- BizDev

## Cost (in USD)

$500

**Comment by benedictvscriticus** [comment]
RIP was consolidated here https://github.com/raid-guild/RIPs/issues/135
