### ISSUE TITLE
DM <> FUX (and friends)

### ISSUE THREAD

**Issue by plor** [raid-guild/RIPs#147]
# Continued iteration on Dungeon Master

### Project Submitted By

plor
._sayonara
0xmaker

## Summary

We plan to incorporate the concept of FUX workstreams into the raid workflow to measure how much availability raiders have and how much they are committing to a given raid. This includes views to display FUX within the Dungeon Master UI and easy methods to
update FUX to signal the current status.

In addition we are tackling the highest priority issues remaining from the previous UX exploration. We assessed from the existing list and voted which we feel is a priority right now. Below is the breakdown of tasks we will ship as part of this RIP and the components for the FUX integration.

~~Milestone 1~~:
- ~~Integrate raids with FUX~~
  - ~~Scaffold collab.land miniapp~~
  - ~~Allow users to manage FUX distribution via discord commands~~
  - ~~Allow clerics to create FUX workstream via discord commands~~

~~1 ETH~~
 
Milestone ~~2~~ 1:
- Add clarification to counts on the several pages
- Fix issue with not being able to remove the "Role Needed" from raid
- ~~Add the ability to edit more data on the raid and consultations~~
- Add a retrospective to the process of completing a raid
- Add the ability to add links to raid assets
- Fix styling with search dialog
- Change default member view to "actively raiding"
- Add tooltip for role badges

1 ETH

Milestone ~~3~~ 2:
- ~~Integrate FUX status with DM~~
  - ~~Display FUX data for workstreams on Raid page~~
- Add `/fux` command to DM Bot
  - links user to fux.gg to create workstream or stake FUX
  - if called from within raid channel, links directly to existing workstream
- Add FUX to DM
  - Tie raid to FUX workstream
  - Display FUX committed on raid screen
~~0.75 ETH~~ 1 ETH (will return excess based on reduced scope)

## Why should we build this?

There are many quality of life improvements in this that should improve the usability of DM. Incrementally improving Dungeon Master as part of other efforts is a great way to get this work done. The FUX experiment is to start using this system to see how it helps us coordinate our availability and commitment so that raiders aren't overcommitted to too many things. By pushing more work through FUX we improve the network effect which helps other projects using FUX to manage obligations.

## Anything else you'd like to add?

Introducing additional people to the Dungeon Master codebase is a side benefit of this RIP. The more people who are able to contribute to this project, the more iterative improvements we'll be able to make in this way. So far the party attached has shown interest in helping on this, but it would be great to have additional people come up to speed on this stack.

## Raid Party Skills Needed

- Archer (minor)
- Warrior
- Paladin
- Monk

## Cost

2.75 ETH

**Comment by plor** [comment]
I set up a smart invoice for this: https://app.smartinvoice.xyz/invoice/0x64/0xdf45b728d6c3443132f2ce9431994dcded150c18/ that pays out to https://app.safe.global/home?safe=gno:0xeebE0880ce0dE027BA03455F4EEC6484Af0AcA3e which includes the project team. Will move to on-chain vote shortly.

**Comment by plor** [comment]
Funding proposal is up: https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposals/15

**Comment by scottrepreneur** [comment]
Shouldn't be building main features for external dependencies that aren't proven in process.

**Comment by plor** [comment]
Updated plan is to scale back scope of milestone 1 and 3 to make FUX available to use, but full integration will come at a later date when it is more clear what value we derive from the protocol. I'll edit the Above to reflect this.

**Comment by plor** [comment]
Scrapping this RIP. Feel free to pick up parts of it at will and keep running.
