### ISSUE TITLE
New Batch of RG Swag

### ISSUE THREAD

**Issue by bennisan86** [raid-guild/RIPs#150]
# Project Idea

### Project Submitted By
Bennisan

## Summary

It's been too long since Raid Guild produced its previous batches of swag, the need for some new material arises! This raid is about the production and distribution of with shirts, hoodies and potentially stickers of new designs (see below) created by me, @bennisan86.

## Why should we build this?

Swag is the most obvious way to increase our visibility at the numerous events we attent, both as individual members and as a whole. Plus it's fun to wear, it feels good to represent the Guild we know and love!

## Anything else you'd like to add?

I designed things that I would love to wear/see myself. (These are a little outside of what we're used to as RG brand, so as a side effect they also re-ignited the conversation about RG's Headless Brand (see Discord)).

A soft consensus for these designs was found at the Round Table of september 7th (presented as https://docs.google.com/presentation/d/1mfBQPZuqz-8Hx6l0xHyZHSJPFbMNz2ZFx03PH2m5ac0/edit?usp=sharing) and by voting in the #design channel on Discord.

### The designs
The different designs are vectorised and are, as of this RIP, considered owned by Raid Guild, and thus part of Raid Guild's collection of illustrations. They are free to be used for any RG purpose .

<img width="1016" alt="Screenshot 2023-09-21 at 11 07 20" src="https://github.com/raid-guild/RIPs/assets/51742196/da11f5e7-aa15-4382-8920-ff2c8aebb454">

<img width="634" alt="Screenshot 2023-09-21 at 11 06 22" src="https://github.com/raid-guild/RIPs/assets/51742196/19a5bff7-191c-46ad-a6e6-d1b3e0ca9d2e">

<img width="801" alt="Screenshot 2023-09-21 at 11 06 07" src="https://github.com/raid-guild/RIPs/assets/51742196/eea86a4a-78d3-44fc-ab67-41616257bc62">

<img width="502" alt="Screenshot 2023-09-21 at 11 25 22" src="https://github.com/raid-guild/RIPs/assets/51742196/3f202b98-93ea-40ef-aea5-7f9c671804ec">

### MetaFactory

Included in this RIP is not only the creation of the designs, but also the followup to production. For this, we want to work together with MetaFactory. Advantages: they handle production and distribution. Each member can visit the shop and purchase the items as preferred. Also the new products will have increased visibility when they are in the MF-shop, potentially attracting buyers from outside of the Guild.

This followup will also be done by me, @bennisan86 and I will report at Round Tables. I will also notify all members when the designs are actually in the shop, available for purchase.

## Raid Party Skills Needed
@bennisan86 as Archer and Monk

## Cost (in USD)

$600 as fixed price for 
- creation of the designs 
- followup to production
- internal communication about this RIP

**Comment by derrekcoleman** [comment]
Bennisan had a call with MetaDreamer on behalf of MetaFactory last week. They're down to put the shirt and hoodie in their shop. Vectorized designs have been created and sent.

Bennisan to follow up with information on the production timeline and clearer check on guild interest before sending 🚀

**Comment by bennisan86** [comment]
Next RT (september 28th) I will share a sort of "pre-order" (by ways of a google form) to get a real feel for who want to actually buy one of these shirts or hoodies.

**Comment by plor** [comment]
https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposal/23
