### ISSUE TITLE
Participate with Raid Guild in the next Grants round

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#152]
# Project Idea

Retroactively rewards community contributors for their efforts in a quadratic funding round.

### Project Submitted By

bitbeckers

## Summary

The next grants round will be focussed on communities and I think it's an interesting oppertunity for our DAO to rewards it's members. 

## Why should we build this?

Because we have a lot of people 'just doing things'. Like EC and Dan running ops, Ape and Derrek running meetings, Christina weaving relations, Plor being forever vigilant and many others I've forgotten here.

Additionally, I think this is a good signal to get Raid Guild under the attention of many (or at least people looking at Grants rounds)

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Grants round operator

## Cost (in USD)

$2500

**Comment by bitbeckers** [comment]
But please document so we can do a retro

**Comment by bitbeckers** [comment]
Update after ongoing conversation during weekly meetings and the forum thread on Discord (# QF Round for DAO members)

* The general consensus is "let's do it" for a funding amount of 2500 DAI
* @bitbeckers will coordinate but would love some extra eyes, support. Coffee-crusher has offered to help with a retrospective questionaire after the round
* We want to set a matching cap so that low participation or wargames can not lead to a single application getting the full matching pool
* There's significant interest in nominating people, so we'll facilitate that in our Discord channels

**Comment by bitbeckers** [comment]
I went ahead an ran through the round setup and will be posting the configuration and some consideration here. This will be discussed in the weekly later today and shared in the Discord channel as well. If we get social consensus, I can spin up the round.

The action items are:

- [ ] 1. Get consensus on round configuration
- [ ] 2. Deploy round and add other round managers/coordinators
- [ ] 3. Create Safe with round managers/coordinators that will receive the funds on Optimism
- [ ] 4. Fund round contract on Optimism
- [ ] 5. Outline applications/nomination process

Items 1-4 are subject to the setup as outlined below.

---------------------------
### Round Setup

* Round Operators
	* There are multiple round operators possible, I nominate myself as one of them but would like a cosigner or two.
	* **Question**: Who wants to be a signer?
* Program
	* [On Round Manager](https://manager.gitcoin.co/#/program/0x7fd862a0489f98e6e4daf215920eb52d722ff2d3)
	* Program name: Raid Guild Contributor Round
	* Operator wallet address; it's now me.
	* We can add/remove round operators.
	* **Suggestion**: Add Sejal/Kieran as round operator so they can be mini-admin to support us.
	* **Question**: Who wants to be a cooperator?
* Round:
	* Public round of Quadratic Funding
	* Name: Raid Guild Contributors Round 1
	* **Support**: Discord; add a quadratic-funding round RIP channel and Forum
	* Matching Pool
		* 2500 DAI
		* Optimism
		* Matching cap: 20%; this means a max cap of 500
		* **Note**: There's the 10% fee towards the Grants Stack
	* Applications
		* Rolling applications
		* Passport; disable it because it's a small round and let's not make it a barrier
		* **Applications start Monday Nov 13 - Thur Nov 30** => Applying and nominating
		* **Rounds open Wed Nov 15 and ends Thur Nov 30** => Funding!
		  * For applications:
			* Socials are optional (Twitter/GitHub)
			* Payout wallet address
			* Email
			* Team size
	* Minimum donation threshold for matching funds:
		* $0.96 (receive 1 dollar minus gas costs)
	* Round Description
		* "This is an round for the Raid Guild community and it's contributors to retroactively rewards community members."
		  * **Suggestion**: add link o RIP post


* Contributor applications and nominations
	* Apply via builder.gitcoin.co and apply to the round via explorer.gitcoin.co
	* Nominate; we nominate a candidate in the forum and they can accept their proposal by submitting an address. After that we'll help 'm onboard
	* **Suggestion**: Both applications and nominations will be subjected to review in the Guild.

* Eligibility criteria; these are not hard-coded but are visible.
	* Raid Guild contributor (Member V2/V3 DAO)
	* Application accepted by the Guild via consensus in meetings or fora.
	* Nomination accepted by the Guild and the nominee via consensus in meetings or other fora.

* Application questions; these will need to be answered by applicants or nominators
	* How long have you been with Raid Guild?
	* What has your, or the nominees, contribution to the Guild been?
	* Are you, or the nominee, an individual or group?
	* Any additional resources you'd like to share?
	* **Question**: Any other questions we want to have anwered in the round operation?

**Comment by bitbeckers** [comment]
We have signers in a Sage (tae + tufnel) and added a Safe as a Round operator in the round:
- Safe: https://app.safe.global/home?safe=oeth:0x1e90271B3Fc6F287a299A60c13b4bE3ddEFD4cde
- Round: https://explorer.gitcoin.co/#/round/10/0xb5c0939a9bb0c404b028d402493b86d9998af55e

We're curating all round application in an internal forum channel

**Comment by bitbeckers** [comment]
Application process:

Steps for application:
- Create a project on [Gitcoin Builder](https://builder.gitcoin.co/#/projects). Here's an example: [bitbeckers | Raid Guild](https://builder.gitcoin.co/#/chains/10/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/1384)
- [Apply with your project]( https://builder.gitcoin.co/#/chains/10/rounds/0xb5c0939a9bb0c404b028d402493b86d9998af55e) in the round

Steps for nomination:
- Create a post in the round forum and `@tag` the nominee
- The nominee accepts the nomination by providing a payout address (required in the application) 

In the Grants round, you'll be asked to answer the following questions:

1. How long have you been with Raid Guild? 
2. What has your, or the nominees, contribution to the Guild been? 
3. Are you, or the nominee, an individual or group? 
4. Any additional resources you'd like to share?

**Comment by bitbeckers** [comment]
Proposal to fund the round contract via some safe-safe-relaying: https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposal/35

**Comment by derrekcoleman** [comment]
[Payout done](https://optimistic.etherscan.io/token/0xda10009cbd5d07dd0cecc66161fc93d7c9000da1?a=0xd2462012e146bb4664d334b24d3cd67ba6c7c7b0)! bitbeckers will do a write-up on the steps and lessons learned. We have the donation data in raw form; a few charts coming soon ™️

**Comment by derrekcoleman** [comment]
bitbeckers to write retro, but on a timeline with respect to his other responsibilities

aka retro soon™️
