### ISSUE TITLE
Add Cookie Jar to V3 DAO

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#153]
# Project Idea

Add a Cookie Jar to a Safe controlled by the RG DAO.

### Project Submitted By

@bitbeckers 

## Summary

We've tested a Cookie Jar using a V3 DAO over the last 6 months, and found it impactful as many people withdrew funds fro scribing, dev, and ops tasks.

https://admin.daohaus.club/#/molochv3/0x64/0x3d5f4ca36da241d64d094dcadc10964282a8cc4c/proposals

## Why should we build this?

The Cookie Jar worked, and got gamed on an open vulnerability. There was a hacked DAO member adress and it could claim all remaining funds. The Cookie Jar app/contracts build by @dekanbro and @bitbeckers solves this.

## Anything else you'd like to add?

We need to align on:
- Period; how often can a member claim
- Token; what token can they claim
- Amount; how much can they claim

## Raid Party Skills Needed

- Blue fur
- Voracious appetite

## Cost (in USD)

-

**Comment by bitbeckers** [comment]
Update: this is pending on a feature @MrDeadCe11 wants to add. After that, we'll roll out a fresh release and go through the proposal flow of setting up a CookieJar for RG and funding it. 

Because it's cool, we're probably going with the 6551 NFT so that we can make the Moloch V4 migration easier

**Comment by derrekcoleman** [comment]
Waiting on Santiago update. SDK update broke something - bb will fix with dekan. Plan B is to mint a cookie jar 6551 NFT that checks if you are a DAO member.

**Comment by derrekcoleman** [comment]
Staying with current implementation for now (bitbeckers has too many FUX)

bb working w/ dekan on front-end. Hoping to get this pet project done 🤞 

_Rowdy offers to help with frontend!_
_MrDeadce11 happy to help with contracts!_

**Comment by ECWireless** [comment]
Updated the frontend app.

@rowdy is starting on the subgraph today.

When subgraph is complete, we can mint a new cookie jar for RaidGuild.

**Comment by plor** [comment]
Temporary solution to be able to pay out cookies in the meantime is $2500 to ganggang to pay out manually. https://gnosisscan.io/tx/0xddcabd0752b3497370126cb91d88a1520e9e2172ddd3416ddb6715e27655ce86/

**Comment by boucherbox** [comment]
Status unsure, reached out to Rowdy to see if he is currently working on this

**Comment by boucherbox** [comment]
@bitbeckers what do we think about compensation for this RIP? Rowdy has carried it to deployment, shall this be dogfooded? shall the DAO put some funds in for pulling?

**Comment by bitbeckers** [comment]
> @bitbeckers what do we think about compensation for this RIP? Rowdy has carried it to deployment, shall this be dogfooded? shall the DAO put some funds in for pulling?

Payouts will be done via the CookieJar Yeet DAO where the Guild also yeeted into: https://admin.daohaus.club/#/molochv3/0x64/0x576579d3fd475e14742bd275e8b2f617f70b874b

**Comment by ECWireless** [comment]
It's been handed over to DAO. Will be spinning up the next iteration of the CookieJar soon as the official one. And that's how the cookie crumbles.
