### ISSUE TITLE
Moloch's Rejects: SEO RODEO

### ISSUE THREAD

**Issue by boucherbox** [raid-guild/RIPs#154]
# Project Idea
October 2022 Degeneroach lead a RIP to optimize the high Domain Rank of the main site to bring more client work to the Guild. Details in the RIP Proposal below. 

https://github.com/raid-guild/RIPs/issues/113

The project suffered Moloch at the implementation stage. The designs were completed but there was disagreement on implementation and build stalled. The FE build was rushed to get the new portfolio section out the door for ETH Denver 2023, kudos to Scott. 

This RIP proposes to: 
- finish the implementation of the designs that Degeneroach created ( https://www.figma.com/file/l5GpxX2LgOCxd7StHujiRQ/RaidGuild---SEO-Rodeo-%23002?type=design&node-id=36-99&mode=design&t=owpUaDccoZUFPrh2-0 )
- fix website display issues (specifically changes on resizing)
- set up Fathom Analytics and google search console for continuing monitoring
- set up event monitoring to track conversion of website visitors into completions (submissions or new apprentices)
- [SEO Scope](https://hackmd.io/aRwyWFZmRwqkmkGucPQRVg)
- Copy writing for the 11 Service pages and updating to the website content via SEO recommendations

### Project Submitted By

Sasquatch

## Why should we build this?

Gone are the days of a line of clients outside the walls waiting for their chance. We need visibility to generate new business. Improving our online presence to draw in more clients passively should be a priority. 

### Focus Points
- Submission Conversion: Event monitoring for click through to Raid Submission
- Join Us Conversion: Event monitoring for click through to Apprentice Application
- Establish Baseline to test future Marketing efforts against
- Create SEO standards for future Raid Guild content creation

## Raid Party Skills Needed

- Design - @degeneroach
- Content - @boucherbox 
- Full Stack Dev - @sayonara
- SEO - @degeneroach + @boucherbox 
- MGMT - @boucherbox 

## Cost (in USD)

FrontEnd Build -------- $1,100
Design ----------------- $1,700
Copy ------------------- $1,700                       
SEO -------------------- $2,400
Total $6,900

## Timeline
Week 1:
- FrontEnd Build
- KeyWord Research and Onboarding
- Technical SEO Fixes

Week 2: 
- Finish FrontEnd Build
- Content Optimization
- Copy Delivered
- Meta SEO work

## On-Going
- Ranking monitoring via Ahrefs, Google Search Console, and Fathom (keywords identified in research and domain)

## Follow-Up Work
- after 3 months, @boucherbox will submit a 2nd RIP. This proposal will be for a report providing evidence of the efficacy of the keywords as implemented in subsequent Raid Guild content. This requires that Raid Guild invest in content creation over the next 3 months, following the SEO best practices established during this RIP. In addition to normal visitor/view/bounce rate information, the foci of the report will be: top refer channels and CTR for submissions and apprentice applications

**Comment by boucherbox** [comment]
Content needs review

**Comment by derrekcoleman** [comment]
[Funded](https://admin.daohaus.club/#/molochV3/0x64/0xf02fd4286917270cb94fbc13a0f4e1ed76f7e986/proposal/29). Kicked off!

**Comment by derrekcoleman** [comment]
Cruising~ Demo next week, ideally.
Sas trying to get portfolio entries from clerics to highlight on the site. sayonara taking designs, Sasquatch and degeneroach working on content. ECWireless and scott helped sayonara get access to gated stuff.

**Comment by derrekcoleman** [comment]
Vercel issue fixed. Content still coming in. Updating buttons (thx vika) is proving tricky (thx nitegeist). Optimistic for Thursday demo.

**Comment by derrekcoleman** [comment]
Remaining tasks have been outlined. Once ._sayonara's cleared, team will be ready to finish up.

**Comment by derrekcoleman** [comment]
Check out new design system updates on Dungeon Master, Hire Us, and so on. _.sayonara will finish soon ™️

**Comment by derrekcoleman** [comment]
_.sayonara implemented EC's feedback. Buttons are finally cute. Scott gave Sasquatch access to more past raid data. Sasquatch parsing data slow and steady~

Waiting on designs for static elements.

**Comment by boucherbox** [comment]
Moving to close this RIP as partially completed. Design, build, Copy and a partial SEO scope was completed and paid out. Have $1100 left in Team safe that will be applied to next iteration of this RIP

@Seroxdesign is conducting a audit and will apply these funds to the next iteration of raidguild.org
