### ISSUE TITLE
Marketing: Content Team

### ISSUE THREAD

**Issue by Fluffy9** [raid-guild/RIPs#156]
# Project Idea
Case studies for 1 Raid Guild project. Let us know if there are any other projects wrapping up. This will entail two meetings with RaidGuild teams to identify success stories/testimonials/cross promotion and follow up with a review + statistics. Two meetings with clients for initial results and a follow up.

We’ll create pieces on two topics in twitter threads, on our blog, and a YouTube video (if we have one). The first topic would be highlighting the technical process of completing this project from start to finish. The second topic would be highlighting the impact/benefits of the client. 
The objective of this project is to establish RaidGuild as the top-of-mind choice for people seeking project support, ensuring that our name naturally springs to their thoughts without the necessity for further research.
We also want to make a retrospective on this project itself. This will be an internal only breakdown of the current/projected long term ROI on this project.

## Project submitted by
@ pupcakes @ vika @ karaisabella

## Raid Party Skills Needed
* Project Manager
* Designer
* Marketer

## Summary
This RIP is to demonstrate RaidGuild's past projects in Web3 development by sharing detailed insights into completed projects. This includes emphasizing project goals, team contributions, challenges faced, and innovative solutions, possibly through Twitter Threads.
Additionally, the initiative seeks to include client testimonials or brief success stories to validate RaidGuild's capabilities and showcase client satisfaction. Visual elements like graphics or snippets will be used to highlight key project aspects, making them visually appealing and easy to understand. Before-and-after visuals or progress snapshots can be included to demonstrate the impact of RaidGuild's work in transforming projects.
To measure the success of these efforts, we will include tracking engagement metrics like likes, comments, shares, and retweets, evaluating conversion rates from profile visits to inquiries with support of the B2B Team (Suede, coffee-crusher) and the newly integrated analytics on the RaidGuild's website. 

## Project Showcases:
* Sharing detailed breakdowns of past projects
* Highlighting the goals, team involvement, challenges faced, and innovative solutions provided (e.g., in a Twitter Thread)
* Success stories with client testimonials or brief statements about their satisfaction.
* We are starting this with Sero and Sasquatch’s project. We also want to ask clients how they found RaidGuild
* Include visually appealing graphics or snippets showcasing key aspects of completed projects, maybe using before-and-after visuals or progress snapshots to demonstrate the impact of the DAO's work
* We’ll develop KPIs to measure success of each case study
  * Pupcakes reached out to Sero and Sasquatch for their project details 
* Call to Action (“Hire us!” or similar) will be included at the end of the Thread to generate more traffic to RaidGuild’s website and eventually turn into business inquiries. 
* Behind-the-Scenes Insights. Offer glimpses into the DAO's internal processes, team culture, or the way projects are managed to build trust.

## Why should we build this?
Our initiative is aimed to enhance RaidGuild’s visibility and credibility as one of the leading DAO in Web3 development. By increasing our presence on social media platforms like Twitter, we aim to increase traffic to the website, particularly to the “Hire Us” CTA, ultimately attracting more clients and strengthening RaidGuild’s reputation in the industry.
Our counterparts are going to submit a RIP in December to do cold outreach sales. We want to support this effort with content that will help close the deals (real numbers on how we’ve impressed past clients). 

## Bonus work, Video Content:
* Recycle the 'brown bag' workshops by summarizing key takeaways, possibly with a quote on graphic → then post a link to the recording
share snippets or teasers of these videos on Twitter to generate interest and direct traffic to the full content on YouTube
* create YouTube channel
* convert Origin Stories to video and social media content

### Cost: 
* 2x YouTube video - 12 hours each. 24hrs x $50/hr = $1200

## Cost (in USD)
**Total: $2.3K per case study**
* Planning - 4 hours
* 4x meetings - 2 hour each
* 2x A twitter thread - 6 hours each
* 2x blog posts - 6 hours each
* 1x retrospective - 10 hours
* 46hrs at 50/hr = 2.3k
* Hunters fee for clients found directly through the content created (tracked by analytics)

## Milestones
1. Preparation - 2 weeks
2. Content Creation - 4 weeks
3. Analytics - 2 weeks

## Timeline
January 8 - February 29 for one case study

**Comment by derrekcoleman** [comment]
Incorporated member feedback, e.g. adding a 10% hunting fee for clients found. Clarified that the initial scope is for a single case study. Changed Pupcakes' role to Monk for clarity.

Done with feedback stage after a few weeks, looking to put up for funding soon.

**Comment by Fluffy9** [comment]
Here are our milestones. The budget has not changed 

# Milestone 1: Preparation & Identifying the 1st Use Case
Week 1-2
Payment: $460 (20% of total budget)

## We Will:

Plan and conduct Initial Meetings: We will hold meetings with RaidGuild members and clients to define project goals, gather essential data, and identify success stories.
Outline Our Project Plan: We will develop a comprehensive content strategy for our Twitter threads and blog posts.
Begin Research & Data Collection: We will collect relevant information, client testimonials needed for our case studies, and hold a meeting with RG members repsonsible for SEO to discuss the tools for collecting statistics.
# Milestone 2: Content Creation & Posting
Week 3-6
Payment: $1,150 (50% of total budget)

## We Will:

Develop Case Studies: We will create in-depth case studies that highlight the technical process, client impact, and success stories.
Create and Refine Content: We will draft, finalize, and review our Twitter threads and blog posts.
Incorporate Feedback: We will seek and integrate feedback from the Raiding Team and clients to refine our content.
Execute Content Posting: We will prepare our content to be posted on Twitter and our blog.
# Milestone 3: Analytics
Week 7-8
Payment: $690 (30% of total budget)

## We Will:

Track Engagement: We will monitor and record engagement metrics such as likes, comments, shares, and retweets, as well as website traffic and potential other metrics identified with SEO Team.
Analyze Effectiveness: We will assess whether and how our content has influenced client inquiries and overall engagement levels.
Note: We know that our social media posts might take a while to catch on with the desired target audience, e.g. potential clients. It’s likely that we won’t see a big jump in client interest right away during this project. Hence, keeping RaidGuild’s name out there and active after this RIP is finished is key to making the most of this initiative.
Conduct a Retrospective Review: We will evaluate the process and overall impact of our project, identifying key learnings and stumbling blocks.
Prepare a Comprehensive Report: We will compile a detailed report of our outcomes, insights, and actionable recommendations for future initiatives.
Total budget: 2300$

Select a repo

**Comment by derrekcoleman** [comment]
Team working, scheduled a meeting with Sasquatch this week. 

Moloch: team member MIA since Christmas; talking about removing her from the RIP. In the meantime, Pupcakes and vika are going to forge ahead.

coffee-crusher.eth throws her hat in the proverbial ring!

**Comment by derrekcoleman** [comment]
Twitter access acquired! Client interview soon! 🤞 for cross-promotion. Brainstorming implementation of "how did you hear about us" field on consultation form with sayonara.

**Comment by boucherbox** [comment]
still soliciting comments on content. @Seroxdesign and @boucherbox highlighted for comment on accuracy

**Comment by Seroxdesign** [comment]
is there a final outcome, i saw the drive which had like 10 images/text but felt incomplete in the sense that it's not put together into a cohesive document

**Comment by vicosv** [comment]
there are two .md files in each folder (external and internal interviews), one for the Twitter Thread and one for the Article. the images are referenced in the .md docs, that's why they are in the folders. I can transfer everything into Google Docs, if that would be easier for you. let me know!

**Comment by vicosv** [comment]
here is the Google Doc with everything with everything put together
https://docs.google.com/document/d/1CrAuyvfsBRwty0kDdQv-3tr7pOZVdqbsqxTm1Y9bQkk/edit?usp=sharing

**Comment by Seroxdesign** [comment]
We need more images to make this work, I believe you've covered a lot in text but gifs of the UI animations as well as more comparative pictures will take this a long way. @vicosv

**Comment by Fluffy9** [comment]
I think we added in all the images from the sources we were sent. Who has these UI animations?

**Comment by boucherbox** [comment]
@Fluffy9  and @vicosv to connect with @ECWireless on getting completed milestones released

**Comment by vicosv** [comment]
We have completed **Milestone 1: Preparation** ($460) & **Milestone 2: Content Creation** ($1,150). 

In this [document](https://docs.google.com/document/d/1CrAuyvfsBRwty0kDdQv-3tr7pOZVdqbsqxTm1Y9bQkk/edit?usp=sharing), you will find: 

- 2 interviews: one conducted with Adz from POKT Network and one with Sasquatch and Sero; 
- 2 blog articles about the POKT Raid from the perspective of the Raiding Team and the perspective of the client; 
- 2 twitter threads capturing the main points from both interviews.

**Content prepared for publishing is here:**

Interview with Sas and Sero: https://hackmd.io/@pupcakes/ry0CMJLWR/edit
cover image for this interview: https://drive.google.com/file/d/1CWRbbn6W3Ju7bewjdhOT4_erPJzK4xf6/view?usp=sharing

Article about the interview with Sas and Sero: https://hackmd.io/@pupcakes/ByS0yJ8WA/edit 
all images for this article: https://drive.google.com/drive/folders/1Bw5JXcnH-vW_2shjtSiOLPg5aWGPwC-o?usp=sharing

Interview with Adz: https://hackmd.io/@pupcakes/ryDa0ABb0/edit
cover image for this interview: https://drive.google.com/file/d/1BEYlqIcCIpNA4zM9zbWLdEeRFISa713H/view?usp=sharing

Article about the interview with Adz: https://hackmd.io/@pupcakes/SJVQpRH-A/edit
all images for this article: https://drive.google.com/drive/folders/1B85GWwTUf6oOKA7XRLwQx9UvFgYQv5bp?usp=sharing

**Comment by ECWireless** [comment]
Paid out here: https://gnosisscan.io/tx/0x4a132c248b2227ec64af08c8ad38ebb126e66769ff1bf9cab35258ca9bac22fa
