### ISSUE TITLE
 🌌 Unleash the Lights for RaidGuild 🌟

### ISSUE THREAD

**Issue by Suede0619** [raid-guild/RIPs#158]
### 🌠 Quest Initiator

**Suede**

## 📜 Tale Overview

Inscribe the RaidGuild emblem upon an 18-story citadel in the heart of Denver during the ethereal ETHDenver2024 gathering.

## ⚔️ Quest Rationale

Find the intricate details of the unfolding epic; include the RaidGuild in the saga detailed here: 
[🌟 CryptoLumenati Spectacle at ETHDenver 2024 🚀](https://hackmd.io/@Suede/B1HJz4vta)

## 🏰 Why Must We Embark?

This venture presents a golden opportunity for immense exposure at ETHDenver2024, delivering a potent impact with a relatively modest investment. 

The projection shall manifest, casting its glow upon the RINO neighborhood. Images shall be swiftly disseminated across the realms with #ETHDenver2024 and #Raidguild, resonating in the retweets and reposts of Guild members.

Thus, a tapestry of allure shall be woven that beckons inquiries from neophytes and seasoned clientele alike. 

Moreover, our noble endeavor stands as a beacon for the salvation of humanity, as RaidGuild endeavors to etch an indelible legacy of breathtaking design and invincible code upon the vast eco-system.

## 🎉 RIP Party Talents Required

- Visionary Projectionist—Suede
- Pictorial Chronicler—Suede and the Brigade
- Architect of Social Media Chronicles—Suede and the Brigade

📍 Join the discourse on logistics: [Telegram Convocation](https://t.me/+16ggncBDEVA1OWJh)

## 💰 Expenditure (in USD)

$190 (Cost encompasses the realm of a one-color stencil, priced at $169, along with taxes, shipping, and set-up)
[GoboSource Wisdom](https://www.gobosource.com/gos/custom-gobos-pricing.php)

**Comment by ECWireless** [comment]
Stencil is being ordered this week. Also trying to put up some messaging around the Senate bill offering more clarity around crypto.

**Comment by Suede0619** [comment]
The stencil was ordered to be delivered to Denver with plenty of time. I learned today that they are made in Italy by a glassmaker there.
Other projects to be projected include Bankless, Cabin, and Stand With Crypto. Public Noun #5, a Moloch will go up.
There will be music, donuts, chai, POAPs, and swag at the event. I received some funding from Metacartel to cover these costs and equipment costs.
I will go out on a previous night to take photographs with a good camera on a tripod.

**Comment by Suede0619** [comment]
Live from the event; I will post twice each to the CryptoLumenati Twitter.
https://twitter.com/cryptoLumenati
And, Farcaster.
https://warpcast.com/suede

Each post will have an image and copy and appropriate tags.  #ETHDenver2024, @RaidGuild

**Comment by Suede0619** [comment]
I need copy for two tweets. One could be around cohorts and joining, and the second around hiring and becoming a client.
The guild should talk about what we want to say. IMPORTANT <<--todo

Ideally, then Guilders would repost those to create virality. Also, anyone at the event would be posting too.

I will post these posts to the TAVERN channel in Discord. You can search @RaidGuild to find the posts. Let's blow it up Friday night and Saturady.

**Comment by Suede0619** [comment]
Copy for two tweets threads for the CryptoLumenati Grand Spectacle:

1)
RaidGuild: Premier Web3 design/dev agency immersed in DAOs, DeFi, and dApps. MetaCartel roots, 9000+ years of expertise. We buidl with speed, precision, and quality. Your ideas, our reality. #Web3 #DAO #DeFi #dApps #BuidlExperts

Consultations
Validate your ideas and get expert advice on how to build, ship and grow your product.

Design Sprints
Fine-tune your product market fit and nail your UX before writing a single line of code.

Full Stack Dev
Make your dApp ideas a reality. Our Raiders are the best in the biz, from contracts to front ends.

Marketing
Level up your meme game and build a compelling narrative for your brand/product.

2)
Join the RaidGuild
We believe workers should be self-sovereign and able to work when, where and how they want, as long as they create high value output. We're looking for top talent that can take things into their own hands and bring unique value to the guild.


Learn New Things
Stay on top of the latest trends and developments while leveling up your skills.

Cartel Culture
We're serious about our work and its impacts on society, but we also know how to have a good time.

Tip of the Spear
Join the ranks on the front lines and make a direct impact on the world around you.

**Comment by plor** [comment]
@Suede0619 would you mind adding the links and details of the event here? I moved to the document phase because I think this would be a great spot to package up all that stuff.

**Comment by Suede0619** [comment]
I posted the event to Walkin, so it was also visible on the ETHDenver 'side events' page.
https://walkin.events/event/%F0%9F%8C%9F-cryptolumenati-grand-spectacle

I had 322 RSVPs, and about 50 people came out on Friday to see the Spectacle in person.
We served hot chai, butter cookies, and Lindt Lindor chocolates.
There was a special music playlist and Cryptolumenati stickers.

We served CryptoLumenati GRAND SPECTACLE POAPS for the event on a poap.xyz live kiosk.
https://kiosk.poap.xyz/#/event/admin/CdaZ7IByjEGNacsmCkxN/507cea27-ac87-46eb-8786-86d63e62a516
GET YOURS to commemorate the GRAND SPECTACLE ^^^^^^

**Comment by Suede0619** [comment]
Social posts Twitter:
https://x.com/cryptoLumenati/status/1763312026871365825?s=20
https://x.com/cryptoLumenati/status/1764056877745189008?s=20

Social posts to Warpcast:
https://warpcast.com/suede/0x87316ca8
https://warpcast.com/suede/0x57a96940

**Comment by Suede0619** [comment]
Drone video and images from the projection events are here. Please use it as you wish. Thank you for the collab! This was super fun, and we will do it again. Keep your eye out for big white walls  🦋

Five drone videos and 12 images.
https://drive.google.com/drive/folders/1ruzJgC96DoJ4g-RN2zqblsq8zZZ5hDz7?usp=sharing
