### ISSUE TITLE
Cookie Jar - Update available chains

### ISSUE THREAD

**Issue by 0x0-mico** [raid-guild/RIPs#193]
| name         | about               | title                                | labels | assignees |
|--------------|---------------------|--------------------------------------|--------|-----------|
| RIP Request  | Bounty for cohort VII | Add updated Graph to Cookie Jar app | RIP    | mico      |

# Project Idea

### Project Submitted By

mico (@belakm)

## Summary

This is a bounty for Cookie Jar by adding different networks (graphs) to its client and adds sorting to jars displayed

## Why should we build this?

This was a bounty submitted here: https://app.charmverse.io/raidguild-cohort-season-7/cj-update-the-graph-endpoints-9476207226159137

![bounty](https://github.com/user-attachments/assets/932efec4-f71b-490d-8c41-4098c9367f3c)

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Frontend

## Cost (in USD)

0.5 ETH \ $1215 USD

**Comment by KodeSage** [comment]
Can I work on this?

**Comment by 0x0-mico** [comment]
closing this, cohort bounties per @dekanbro werent meant to be posted here
