### ISSUE TITLE
Consultation + Commission Process

### ISSUE THREAD

**Issue by amsos** [raid-guild/RIPs#25]
# Project Idea

### Project Submitted By

Aaron Soskin

## Summary

As Raid Guild grows and takes on more and bigger raids, we need to find a more efficient and fair way to compensate members during the consultation process and increase incentives to complete.

More info can be found [here](https://hackmd.io/ACc1s26XTxGuizAoZoVjnQ)

## Why should we build this?

We want to both create a fairer way to incentivize and pay members for helping on the sales process.  As projects increase in scope, Devs and Designers need to be brought in earlier in the process to help scope the project.  By adding a commission percentage (based on the total project budget), we're able to split up the commission across the SMEs, Monk, and Clerics who helped close the sale.  By allowing this to be separate from the consultation process, we can continue to provide appropriate incentives to the consultors as well. 

## Anything else you'd like to add?

Not at this time.

## Raid Party Skills Needed

- Raiders

## Cost (in ETH)
2.5

**Comment by plor** [comment]
I'm not sure if this was ever funded, but I think this RIP is worth referencing for future work on the consultations. Particularly of interest is the recent RIP #89 which tackles the process of compensation for bringing in new clients. Would it be worth transferring the insights of this RIP to a formal `.md` file in this repo for building on by future efforts?
