### ISSUE TITLE
RIP-32: Formally Adopt the Guilder's Code of Conduct

### ISSUE THREAD

**Issue by topocount** [raid-guild/RIPs#32]
# Guilders' Code
## Why
The ethos of the RaidGuild is semi opaque, in the sense that it's an unspoken code of conduct or way of treating each other & our clients. We have gotten to the point where having unspoken codes of conduct just won't cut it anymore. This is a special, close-knit group and we must continue to act as such.

Moving forward this will be a canonical document to point people to. To raid you must abide by these standards. 

## The Code
1. Let your work speak for you
2. Treat everyone with Respect
3. Be honest and transparent in discussion and negotiation
4. Receive Feedback Thoughtfully (from Clients and fellow Guilders)

The bottom line: **Let's Trust and Respect each other**

### Standard 1: Let your work speak for you

When a milestone is completed and spoils have been won, we split them in a way that is amiable for all. Let other Guilders tell you what a good job you did and trust them to honestly appraise your work and reward you accordingly. Don't try to carve out a piece of the pie for yourself based on the merit you deserve. Let your teammates cut you a slice.

If, however, there is a special circumstance where finances are tight, be honest with your teammates and let them know. They'll probably bend over backwards to get you your share as quickly as possible and might cut you an extra slice from a milestone (as an advance) if the situation allows.

### Standard 4: Receive Feedback Thoughtfully

Raiders hold one another to higher standards. These standards might exceed customer expectations, but that's because one person's work represents the entire Guild, and other Raiders want to be proud of the work we're doing, whether or not they're directly responsible for it. 

Because of this, Guilders are encouraged to review and provide feedback on other's work, and those responsible should receive that feedback with the understanding of who they're representing and they should also understand that feedback is an opportunity to improve.

If a dispute arises, House Keepers can mediate it, but they will have fair claim to X% of the raid payout.

## Traits of an Effective Guilder

- Candor 
- Impartiality
- Humility
- The Work Should Speak For Itself 
- Kinship (fraternal, long time-horizon-oriented relationships)

**Comment by plor** [comment]
I'm going to close this for consideration as it hasn't moved for a long enough period. I think this type of Code of Conduct could do well as a Poster document with the new boost in DAOhaus, and if these words still hold true we should consider adopting them. Anyone feel free to reopen this if this effort should move forward.
