### ISSUE TITLE
RIP: ToKanBan, A Tokenized Kanban Project Management Board

### ISSUE THREAD

**Issue by matthewcarano** [raid-guild/RIPs#33]
# RIP: ToKanBan
![](https://i.imgur.com/CwCxp3U.png)

## Goal
A tokenized Kanban style project management board that allows clients to *fund* the entire board (project) and/or specific cards (tasks). 

## Why?
To create more transparency on RaidGuild projects, for clients, Raiders, and the community. Funds are pledged per task, and as tasks are complete, funds are released to the Raider who completes them.

Everyone in and out of the project can see all tasks needed to complete it, a clear breakdown of funds designated for the project and each task, who has claimed the task to work on, and what the result is. When the board is cleared, the project is done, and everyone who participated gets an NFT badge. We all win!

## How

**Step 1.** 
![](https://i.imgur.com/fJhT0E2.png)

A client hires RaidGuild to complete a project, in this case to build a website. The Project Manager sets up a ToKanBan board for the website project. The board is a contract that holds and distributes the project's funds. The client sends funds to the board wallet.

**Step 2**
![](https://i.imgur.com/QHlJsUh.png)

The Project Manager adds cards to the project board. Each card represents a task that needs to be completed to finish the project.

**Step 3**
![](https://i.imgur.com/W3EuOk1.png)

The project manager may allocate funds for an entire board list (sub project), or each card (task), depending on how granular they or the client want to be.

**Step 4**
![](https://i.imgur.com/cyovXjk.png)

Raiders who want to participate in the project can claim cards (tasks) they wish to complete by adding their pubkey to the card.

**Step 5**
![](https://i.imgur.com/mpk1nsF.png)

Once the task is complete, the Raider uploads proof to the card. or example a screenshot of copy they wrote for the website. If accepted, the Project Manager signs off on it, releasing the card funds to the Raider.

## Earned Reputation
After all tasks are completed and signed off on by the Project Manager and client, the board contract sends an NFT badge to all Raiders who worked on the project. 

**Yay! A job well done!**

## Notes

Hat Tip to EthKan, conceived by my team members at Swarm City, but never funded: https://www.ethkan.io/

OpenSource KanBan board: https://wekan.github.io/

This doubles as a transparent fundraising tool. Build your board with all tasks needed to complete your project. Your community may fund specific tasks they want to see accomplished.

I would LOVE to bring this to life.

Thank you!

**Comment by plor** [comment]
It seems like this should integrate with Smart Invoice. Has that discussion happened?

**Comment by matthewcarano** [comment]
> It seems like this should integrate with Smart Invoice. Has that discussion happened?

I'm not familiar with that application
