### ISSUE TITLE
RIP: Calendar Fairies (keepers of the shared calendar)

### ISSUE THREAD

**Issue by mprimi** [raid-guild/RIPs#38]
# Calendar Fairy (Discord role)

### Project Submitted By

mprime (season0 cohort)

## Summary

Most of the Raid Guild events (both one-off and recurring) are currently not listed in the shared calendar.
It would be great to find all events in one place.
But keeping the calendar updated is a manual task that never ends.

I'd like to propose to tackle this problem as follows:

Create a new Discord role: Calendar Fairy
Members should be added manually, and they should be given write access to the shared guild calendar.

Anyone else can then call in a fairy when they want to add something to the calendar, example:
```
...
Foo:  It's settled then, let's meet with the client on Tuesday 10PM
Foo: @calendar-fairy can you please add this ☝️ to the calendar?
Bar: @Foo Done!
Foo: Thank you @Bar!
```

or:

```
Newb: What time is the Friday happy hour again?
Foo: Every Friday at 12PM (Pacific) (@calendar-fairy can you please add this recurring event?)
Bar: @Foo Done!
Foo: Thank you @Bar!
```

## Why should we build this?

A consistently up to date shared calendar can go a long way for asynchronous collaboration, especially across timezones.
Seasoned raiders and newbies alike could benefit.

It is also an (almost) zero effort to set up (one-time setup is a few clicks in Discord and Google calendar).

## Anything else you'd like to add?

Someone needs to act as gatekeeper for the fairy role and calendar permissions. Maybe the Innkeeper?

## Raid Party Skills Needed

- Basic understanding of Google Calendar 

## Cost (in USD)

\$0

**Comment by itsencrypted** [comment]
Google Cal delivered on March 12th at Cohort0 #projects channel: https://discord.com/channels/684227450204323876/817850251464540160/820056947939999745

**Comment by mprimi** [comment]
Thank you for sharing that calendar @itsencrypted. I think it's an excellent starting point. 
However sharing via .ics has a fundamental limitation: people won't receive future updates/changes/events. It is a one-time import into people's local calendars.

What I was proposing here is the next step:
 - A **shared calendar** so people can stay up-to-date with new events, time changes
 - A **role** to designate curators/maintainers of that calendar
 - A **process** that makes it easier for everyone to add/modify events on the calendar
