### ISSUE TITLE
RIP: Bard

### ISSUE THREAD

**Issue by jaclynlenee** [raid-guild/RIPs#42]
# Project Idea

**Introduce the role of Bard** in a 3-month experiment to ramp up efforts on social media with the goal of driving more traffic to RaidGuild.org and our suite of tools.

## Problems this Solves

- Hot potato game of who controls which social media accounts, and lack of clarity around who’s responsible for reposting and retweeting stuff.
- Constrained bandwidth of our beloved Tavern Keeper who doesn't have enough hours in the day to retweet all the things.
- Accounts going stale because raiders forget about them (such as Medium which was almost a year behind on 'State of the Raid' posts until it was pointed out recently).

## Summary

**Bard will have the chief responsibility of broadcasting all the awesome content produced by guild members:**
- Like House Keeper, but for our Raid Guild media accounts
- Assistant to Tavern Keeper and Scribe
- Explicitly not a content-creation role, moreso a content reposting role
- Time-permitting will also assist with engagement on posts in our account

**As part of this RIP we'll also:**
- Create a shared record of all our social media accounts, so that any person filling the role of Bard can access keys to these accounts, or be pointed to the person who holds the keys
- Update RaidGuild.org with calls-to-action to subscribe to our channels
- Document + systemize the process for future Bards

[+ Read more details in our project doc](https://docs.google.com/document/d/1-U6vBn69NzHEZI3Z3q--YeCHhR52M-8ve4ayHP6MNpI/edit?usp=sharing)

## Why should we build this?

Twitter is consistently the top driver of traffic to RaidGuild.org

- More engagement on that platform = more referrals
- More potential clients + recruits landing on our website
- More attention on our products (Smart Invoice, WrapETH, etc)

We can double-down on social media efforts to accelerate our growth.

## Cost (in USD)

$4,000

### Project Submitted By

Jaqi

## Raid Party Skills Needed

- PM + Front-End  ( Jaqi ) to coordinate Bard process and make website updates
- Scribe + Shill ( Taekikz ) to play the role of Bard and systematize it
- Illustration ( Charingane ) to create a pixel character for Bard

## Follow Up

Analytics:
- At the end of the 3 months, we'll analyze the data to determine if the Bard’s role engaging in social media accounts contributed to increased traffic to RaidGuild.org and our suite of tools.

Long-term:
- Once we create a playbook for Bard responsibilities, anyone can take this on. If this experiment is successful, we can consider making this a rotating role switching off each month, a shared role, or an ongoing thing for the right person

**Comment by scottrepreneur** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/44
