### ISSUE TITLE
RIP: Dot Org

### ISSUE THREAD

**Issue by jaclynlenee** [raid-guild/RIPs#44]
# Project Idea
Upgrade RaidGuild.org

### Project Submitted By
Jaqi & Saimano

## Summary

A collection of related upgrades to improve the performance, functionality, and style of RaidGuild.org. Raiders have made many suggestions on how to improve our website for usability. This project aims to unify that effort and break it down into phases prioritized by value to the guild.

## Why should we build this?

RaidGuild.org is the hub that connects clients, apprentices, raiders, and investors with tools & resources for how to interact with the guild.

## Anything else you'd like to add?

[Read this doc for more details](https://docs.google.com/document/d/1Pb0oqqSoIi115d4uOWTFnUk4T-O7GI4EwDD2VKYvE44/edit?usp=sharing)

These funds cover chapters 1-3 in the project timeline we've put together.

## Raid Party Skills Needed

Saimano  –  front-end, back-end, bot dev, styling
Jaqi  –  coordination, product, UX
HarryMrtin  –  wordsmithing
Bingo  –  design
Lucas  –  design
Scottrepreneur  –  technical advisor

## Cost (in USD)

$7000

**Comment by scottrepreneur** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/65
