### ISSUE TITLE
RIP:  RAID Token Project

### ISSUE THREAD

**Issue by amsos** [raid-guild/RIPs#45]
# Raid Token Project

### Project Submitted By

Aaron 

## Summary

We've been holding weekly working groups for the past couple months to work through and design a token for Raid Guild.  Recently, we've increased the meetings from 1 a week to 2-3 per week and have started pulling more Raiders into the working group as we move closer to build and implmentation.

Now that we've reached the building stage, we've had to require Raiders to do work outside the defined meeting times as well as starting to development the token and surrounding infrastructure (UI, governance DAO, minion, GtM).  This RIP is to create a budget to start paying the working group members for their time at the beginning of the project as well as pay Raiders who are helping build and finalize the token.

## Why should we build this?

Launching a token will give Raid Guild liquidity to keep the work wheels turning even during bear markets.  This allows us to build RIPs that will either increase effeciency for Raid Guild or Raids that create public good projects for the ecosystem. 

## Anything else you'd like to add?

Nothing else right now.

## Raid Party Skills Needed

- PM
- Content
- Full Stack Dev

## Cost (in USD)

\$15000

**Comment by scottrepreneur** [comment]
12k final budget for this RIP
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/86
