### ISSUE TITLE
(Draft) RIP: Cleric Process Research/Training 

### ISSUE THREAD

**Issue by bingothedesigner** [raid-guild/RIPs#52]
# Project Idea

### Project Submitted By

miss_bayley and bingo the designer

## Summary

We hypothesize there are ways to standardize a cleric's work in Raid Guild which will save clerics time and headache, present a more unified battle front to clients, and make it easier to bring new clerics up to speed faster. We also seek to safeguard against financial loss through Cleric error or oversight. We propose a project with two phases:

Phase 1: Update and polish the current Cleric Checklist document, (https://hackmd.io/ob6Od8a0STSfMzk-De9JWw?both)
Also, create an adoption plan to help the checklist become a part of the regular flow.

Phase 2: Train current Clerics/incoming cohort.
At least 10 active clerics identified, there may be more in the most recent or upcoming cohorts who could benefit from this resource as well. Some have already received Smart Escrow training, but we may include training in both the checklist and the app if there are additional topics to cover, like establishing gnosis wallets.

## Why should we build this?

-To avoid the worst-case financial loss, through either risky payment arrangements or simple human error, that can result from a lack of Cleric training. The Guild's most important function is arguably to facilitate Raids, and if Raiders aren't paid, that can't happen. Clerics are both the most important point in this process, but also the most vulnerable.

-To increase adoption of Smart Escrow. When used properly, Smart Escrow eliminates almost all the risk of a client refusing to pay for work. But it does require a lot of extra work on the Cleric and the Client's part, and if used improperly, can risk losing access to locked funds entirely.

-To increase Raid Guild's scalability. High-performing Clerics (and Monks, the roles often overlap) are the key to ensuring Raid Guild can grow while maintaining high standards of quality on Raids. This documentation and training should help new Clerics get up to speed, and new Raiders to have a better experience as they get deeper into the Guild.

## Anything else you'd like to add?

Reference documentation:
https://hackmd.io/ob6Od8a0STSfMzk-De9JWw?both the cleric handbook WIP
https://hackmd.io/rSBs449PTxC2APZqGNZD4A the current proposal template

## Raid Party Skills Needed

UX Design, which we have covered.

## Cost (in USD)

$5,000

**Comment by plor** [comment]
I'm going to close this RIP, but feel free to reopen or reference other work done on the same vein as this.
