### ISSUE TITLE
RIP: MCON Website

### ISSUE THREAD

**Issue by burleebau** [raid-guild/RIPs#53]
# Project Idea

MCON (MetaCartel Conference) is coming up with an in person event being hosted in Denver, CO **September 15th - 17th**.  The announcement post can be found [here](https://forum.metacartel.org/t/mcon-metacartel-invades-the-west/1189).  

MetaCartel has served a core function in the DAO community and has driven material benefits to Raid Guild, helping to grow to the level it is operating at now.  Additionally, we are aligned with the wider goals of MetaCartel community to create decentralized systems of scale and facilitate access to web3.

Given our special relationship with the Cartel, we would like to sponsor MCON by building a website and a landing page to host all of the content, and supply the necessary resources for organizers to effectively mobilize people to book flights and coordinate reservations preceding the event.  

### Project Submitted By
- Bau

## Summary

A website built by @jonathanprozzi with designs completed by @louxuol 

### Design Assets
- custom chili logo 
- custom flyer
- various pixelated designs

### Website contents 
- event calendar
- sponsor submission
- sponsor pitch deck 
- general information 
- links and embeds
- custom design fully implemented
- hosting the event details and providing a landing page for MCON (MetaCartel Conference) in Denver, CO.

## Why should we build this?

Should RaidGuild decide to move forward in building this, it will help the the MCON organizers tremendously to facilitate attendance to the conference and make sure the event is a success.  RaidGuild can also ask for some sponsorship package that we believe is fair based off of our contribution and is reflective of our communities involvement in the MetaCartel and DAO ecosystem.

This website will serve as a great memory and might possibly evolve into something greater for the MetaCartel community, so building it would mean being directly involved in a structurally important and possibly might be reflected on as the catalyst for generating the excitement and joy necessary to get people attending the conference!  

## Anything else you'd like to add?

If you're interested in participating or providing your input, jump into the #rip-mcon-website channel

## Raid Party Skills Needed

- Design
- Front End Dev
- Cleric

## Cost (in USD)

\$2,500

**Comment by YalorMewn** [comment]
Let's do it, the MCON event is going to be a massive value add to all the DAO's in attendance and having RaidGuild build the event page is just another great notch in our belt + it would qualify for sponsorship perks.
