### ISSUE TITLE
RAID Distribution for Tom  |  Integral 

### ISSUE THREAD

**Issue by Tom-Integral** [raid-guild/RIPs#61]
### Request Submitted By

Tom  |  Integral#1018

## Summary

Was not included in the initial distribution, due to a delay in processing my membership to the Guild. After discussing with a number of members, it was agreed that I could be retroactively included, as it was an unusual case with a number of RG related factors. 

## Amount of RAID Request (in RAID)

Similar Raiders received around 170,000 

Have worked on 14 Raids with a grand total billing of +/- $180k

_below are the reference amounts on initial distribution

| type   | min        | 25 percentile | 50 percentile | 75 percentile | max           |
|--------|------------|---------------|---------------|---------------|---------------|
| raider | 20,461.73 RAID | 110,497.78 RAID   | 140,236.71 RAID   | 231,747.54 RAID   | 2,139,420.74 RAID |
| client | 62,878.40 RAID | 62,878.40 RAID    | 188,635.19 RAID   | 314,391.98 RAID   | 691,662.35 RAID   |

## Address to receive the RAID

0x5562B57D27DdeD14a387C2899a7471C62a3EcA22

## Request Type
_mark all that apply_
- [ ] RAID Correction (fixing a mistake made on the drop)
- [ ] RAID Reward (rewarding community with RAID)
- [x] RAID Retro (was not part of the initial drop but should've been)

## Anything else you'd like to add?

Not at this time.

**Comment by scottrepreneur** [comment]
In support

**Comment by amsos** [comment]
This needs to be considered with the Season 0 drop as well.

**Comment by amsos** [comment]
Going to take 30k out of hte Season 0 request

**Comment by dtolsen** [comment]
Season 0 $RAID request has been created and excludes Tom per above comments.

**Comment by dtolsen** [comment]
Proposal submitted to Raid Guild DAO
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/261

**Comment by dtolsen** [comment]
Tom confirmed receipt of RAID. Closing ticket.
