### ISSUE TITLE
Season 2 $RAID Airdrop

### ISSUE THREAD

**Issue by smombartz** [raid-guild/RIPs#63]
# Project Idea

### Project Submitted By
Sascha, Derrek & xivanc01 on behalf of all Season 2 Members

## Summary
Raid Guild suggested that they wanted to airdrop 30k $RAID to each Season 2 Member.

## Why should we do this?
This is meant as a thank you for Season 2 Members work and participation and in preparation for Season 2 Apprentices becoming Guild Members.

## Anything else you'd like to add?
**Process**
This RIP gets approved, $RAID tokens will be sent to Season 2 DAO, each member will get 30k $RAID disbursed from the Season 2 DAO.

## Cost
**1,200,000 $Raid**
30,000 $RAID x 40 (Season 2 Members)

**Comment by koloz193** [comment]
is there a mechanism by which the airdrop will be done? i.e. just by sending to addresses or in the form of a merkle claim?

**Comment by derrekcoleman** [comment]
We'll probably just send it directly to the cohort members' address

**Comment by Musashi13** [comment]
What if we did not complete our raid?

**Comment by amsos** [comment]
Was the proposal accepted?

**Comment by plor** [comment]
It looks like this was never put on chain. Discussing it today brought up people interested in having this go through.

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/366
