### ISSUE TITLE
RAID request missed from initial drop

### ISSUE THREAD

**Issue by stevelith** [raid-guild/RIPs#64]
# Request Name

### Request Submitted By

sjdthree

## Summary

I've been a client for ~6mo and spent around 70,000 wxDAI so far and look forward to spending more.

## Amount of RAID Request (in RAID)

Amount that works for a client who has spent 70,000 wxDAI and looking to spend another 100,000 wxDAI over the next year at least.

_below are the reference amounts on initial distribution

| type   | min        | 25 percentile | 50 percentile | 75 percentile | max           |
|--------|------------|---------------|---------------|---------------|---------------|
| raider | 20,461.73 RAID | 110,497.78 RAID   | 140,236.71 RAID   | 231,747.54 RAID   | 2,139,420.74 RAID |
| client | 62,878.40 RAID | 62,878.40 RAID    | 188,635.19 RAID   | 314,391.98 RAID   | 691,662.35 RAID   |

## Address to receive the RAID
0xa77e704fe0C7Ec6bA0B881352c3634ccc0E3513e

## Request Type
_mark all that apply_
- [ ] RAID Correction (fixing a mistake made on the drop)
- [ ] RAID Reward (rewarding community with RAID)
- [x] RAID Retro (was not part of the initial drop but should've been)

## Anything else you'd like to add?

Thanks for all your help and recent fixes to some of my woes.

**Comment by dtolsen** [comment]
This issue is complete and can be closed. Client confirmed receipt of tokens. Thanks.
