### ISSUE TITLE
Retro RAID Distro for earth2travis

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/RIPs#66]
# Retro RAID Distro for earth2travis

## Request Submitted By

@earth2travis

## Summary

Membership proposal was in process during the drop. Proposal was delayed while waiting to complete a RIP.

**Work prior to Membership**:

- Season 1 Cohort
- Web3 Site Template
- Client Consultations
- **RIP**: Dungeon Master UX Sprint
- **RAID**: Busting ass on Fraktal since June

## Amount of RAID Request (in RAID)

110,500 RAID

_below are the reference amounts on initial distribution

| type   | min        | 25 percentile | 50 percentile | 75 percentile | max           |
|--------|------------|---------------|---------------|---------------|---------------|
| raider | 20,461.73 RAID | 110,497.78 RAID   | 140,236.71 RAID   | 231,747.54 RAID   | 2,139,420.74 RAID |
| client | 62,878.40 RAID | 62,878.40 RAID    | 188,635.19 RAID   | 314,391.98 RAID   | 691,662.35 RAID   |

## Address to receive the RAID

0xBC5b552641e5d203f0a6C230aA9dC14DA7450053

## Request Type

- [ ] RAID Correction (fixing a mistake made on the drop)
- [ ] RAID Reward (rewarding community with RAID)
- [x] RAID Retro (was not part of the initial drop but should've been)

## Anything else you'd like to add?

Will probably spend it all on Monsters and pools.

**Comment by amsos** [comment]
Approving this request and subtracting his portion from the season 1 drop

**Comment by earth2travis** [comment]
Proposal submitted on DAOhaus App: https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/286
