### ISSUE TITLE
Origin Stories/Freelancer Handbook (season2 cohort RIP)

### ISSUE THREAD

**Issue by TravisWyche** [raid-guild/RIPs#68]
### Project Submitted By
TravisWyche#2116

# Origin Stories/Freelancer Handbook Funding Proposal
## Background
RaidGuild origin stories reveal the complex, nested relationships with other DAOs in the ecosystem. The story of RaidGuild has been told in other forms, in other forums, but this is an opportunity for RG to exercise it's own voice and shape it's own narrative through the curation of an evolving mythology. Apprentices in the season2 cohort described a sharp barrier of entry, with many individuals proclaiming they did not understand how RG was related to other DAOs. Some struggled to find a niche where they would be of best service. This RIP provides cultural context from guilders that are now thriving, allowing apprentices to locate themselves through the presented roles and shared experiences. The freelancer advice will provide tips and tricks that explore the idiosyncratic roles and success stories of veteran raiders that have successfully navigated the onbaording gauntlet. 

## Summary of Problem Space
**Breaking into web3 is challenging (especially on your own)**
- It’s hard to figure out where you fit in, fighting back imposter syndrome, or even transitioning into a freelance lifestyle
- Seasoned RG-ers have invaluable advice, but no easy way to share it (everyone’s busy, and having the same one:one’s gets exhausting)
- There’s a disparity between RG’s internal culture and it’s external comm’s. There’s a lot of eclectic and down-to-earth personalities within the guild and we would love to shine a bit more light on the human-elements of the DAO. 

## Solution
- Create a working group that can schedule, interview, transcribe, and publish interviews with seasoned raiders. This helps them share their advice, origin story, & experiences. 
- Reduce that barrier to entry and help newcomers, especially newcomers with less traditional paths or experiences, feel welcome within the guild.

**Two Pathways:**
- Origin stories: shed light on the pathways different raiders took to discover their niche in web3. 
- Web3 Freelancer Handbook: can provide tips, tricks, and advice on the mindset and workflows that are RG-tried-and-true

## Deliverables
* Interviews with veteran raiders, uncovering their origins and illuminating their onboarding experiences in transitioning to web3 freelancing (5 interviews already completed)
* A new appendage to the website (MVP already produced)
* An internal repository of interviews that might be referenced by healers, archers, rangers, scribes, and other RG roles interested in synthesizing the research for internal ops, applying to external client applications, or simply clarifying the vision of RG
* Branding and illustrations that double as highly sharable/memeable content across other platforms (unique to each interview)

### Supplemental / Speculative Deliverables (to be added later, not accounted for in budget)
- Mini-podcast series from interview audio
- Expand interviews to encompass apprentice experiences: similar form, focused on the onboarding experience, supplemental to the web3 freelancer section
- NFTs! RPG/D&D-style character stat-sheets that can be used by RG members as an avatar (Discord, Twitter, etc). Derived from the unique illustrations generated for each interview. Might be auctioned/sold during events to fund raise $$$ and attention to the Guild.

## Methodology
* Cleric/Monk gather interviewees, provide an introduction to the project, schedule meetings, manage contributors
* Scribes conduct interviews, generates rough transcription, polish text, deliver markup file
* Archers generate illustrations and integrate text onto design
* Warriors have created a CMS website to push updates
* Bards extend the material to other outlets (social media outlets, podcasts, marketing initiatives, *State of the Raid* newsletter, etc.)

## Raid Party
@jengajojo (cleric/scribe/monk)
@traviswyche (cleric/scribe)
@liquidiot (scribe)
@jordanlovesred (archer)
@chiali (archer)
@kevinc (warrior)
@thebeyondr(warrior/archer)
@nitegeist(warrior)

### Monthly
* scheduling meetings, project management, meeting notes (cleric/monk)
* 2-4 interviews with RG veterans (scribe)
* transcript editing (1-3 scribes)
* illustration/design (1-3 archers)
* front end dev (warriors)
* adapt materials for RG newsletter, social media (bard)

- All contributors are compensated via monthly Coordinape rounds
- The total bounty to be Coordinaped is renewed each month based on the number of interviews produced by the squad
- All invoices are billed on the 1st of the month for all interviews delivered in the previous month. 
- Coordinape timeframe and distribtuion date to be decided by consensus of squad members on monthly basis.

**Comment by plor** [comment]
I think this RIP would be a good candidate to be made permanent in a `.md` document in this repo. I can't find the proposal for this, but I feel like it exists. Would anyone be able to provide the link?

**Comment by plor** [comment]
This has been in proposed for quite some time @TravisWyche could you give a brief summary of the outcome of this and any links to funding or anything. Also if you feel a permanant markdown would be useful, they live in `PROPOSALS` on this repo.
