### ISSUE TITLE
RIP: RG Styleguide

### ISSUE THREAD

**Issue by bitbeckers** [raid-guild/RIPs#71]
### Project Idea

Update and finalize RG Styleguide

#### Project Submitted By

bitbeckers & scottpreneur

### Why should we build this

As we have an expanding set of products it's efficient to harmonize and centralize all the styling efforts done in multiple repositories. This way, we build a uniform housestyle so products can easily express the RG feel. Adrienne has a nice set-up for structuring a Figma which delivers a Figma library so the design cycle can be sped up as well. Additionally, when these can be translated to ready made components it speeds up the development cycle.

### Anything else you'd like to add?
Efforts have already been done in the rip-styleguide channel. However it is not complete and we would like to have it be complete so we are ready for a cohort (season 3?) to build components based on the styleguide.

Most time and complexity will be aggregating, organizing and creating the styling in Figma.

For more information/history see the #rip-styleguide channel.

### Deliverable
Figma document presenting the latest and greatest RG styling, similar to the one set up for [DAOHaus](https://www.figma.com/file/Dg2bUjCEILaCnGJsa4bRA0/DAOhaus-Pattern-Library?node-id=6%3A22)

### Raid Party Skills Needed

Ailts - figma designs 
Adrienne - reviewing expert
jordanlovesred - figma designs

### Cost (in USD)

Ailts - 2000
jordanlovesred - 1600
Adrienne-400

Total 4000

**Comment by plor** [comment]
Can we link the styleguide updates from this RIP here? I'm trying to close out the RIP requests in Final and want to make sure all deliverables and documentation that should result from a RIP is accounted for.

**Comment by plor** [comment]
Saw a demo of this yesterday and it looks super cool. Great work.

**Comment by bitbeckers** [comment]
> Can we link the styleguide updates from this RIP here? I'm trying to close out the RIP requests in Final and want to make sure all deliverables and documentation that should result from a RIP is accounted for.

@plor sorry for missing this.

Storybook: https://raid-guild.github.io/design-system/
Repo: https://github.com/raid-guild/design-system

Payouts are already done

**Comment by plor** [comment]
@bitbeckers the last step in the process of a RIP is to submit a PR with a markdown document in the PROPOSALS directory of this repo. It can be the proposal with any documentation of the outcomes to share the change that took place.

**Comment by bitbeckers** [comment]
@plor created a PR and added you as reviewer
