### ISSUE TITLE
Season 1 $RAID Airdrop

### ISSUE THREAD

**Issue by nintynick** [raid-guild/RIPs#73]
[Duplicating #63 for Season 1 per discussion at Token Talk today 12/2/21.]

### Project Submitted By
@nintynick on behalf of all Season 1 members.

## Summary
Raid Guild suggested that they wanted to airdrop 40k $RAID to each Season 1 Member.

## Why should we do this?
This is meant as a thank you for Season 1 Members work and participation and in preparation for Season 1 Apprentices becoming Guild Members.

## Amount of RAID Request (in RAID)

1,480,000 $Raid
40,000 $RAID x 37 (Season 1 Members) [not including @earth2travis who is covered by #66]

_below are the reference amounts on initial distribution

| type   | min        | 25 percentile | 50 percentile | 75 percentile | max           |
|--------|------------|---------------|---------------|---------------|---------------|
| raider | 20,461.73 RAID | 110,497.78 RAID   | 140,236.71 RAID   | 231,747.54 RAID   | 2,139,420.74 RAID |
| client | 62,878.40 RAID | 62,878.40 RAID    | 188,635.19 RAID   | 314,391.98 RAID   | 691,662.35 RAID   |

## Address to receive the RAID
https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158

## Request Type
_mark all that apply_
- [ ] RAID Correction (fixing a mistake made on the drop)
- [ ] RAID Reward (rewarding community with RAID)
- [X] RAID Retro (was not part of the initial drop but should've been)

## Anything else you'd like to add?

Process: this RIP gets approved, $RAID tokens will be sent to Season 1 DAO, each member will get 40k $RAID disbursed from the Season 1 DAO.

**Comment by alcibiadeseth** [comment]
What about those of us who were in season 1 dao under a different name/address and eventually joined as a member post season? Are all members of that dao getting an allocation? Or only those who later became full members?

**Comment by nintynick** [comment]
<img width="685" alt="Screen Shot 2021-12-20 at 10 45 06 AM" src="https://user-images.githubusercontent.com/10171948/146794199-47ccde11-7beb-4c9c-98ab-6f3cca9db794.png">

Season 1 voted via strawpoll to "distribute 40k RAID to each person via proposals to the S1 DAO, then return the rest to the Raid Guild treasury" - this decision is now being ratified on chain here: https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158/proposals/44

**Comment by nintynick** [comment]
Proposal to Raid Guild DemoNick Minion to send RAID to S1 DAO passed and can be found here: https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/265

**Comment by nintynick** [comment]
We have decided to use a Disperse Minion to distribute 40k RAID per person who identified themselves here:
- https://docs.google.com/spreadsheets/d/1fhjQhIDaZiuNKKrLwgb7yofYacXxQqnUTJ-obQ_OVis/edit#gid=0

We tested the Disperse Minion here:
- https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158/proposals/46
- https://blockscout.com/xdai/mainnet/address/0xA5aece57658d5cD31B9F9AeAD6B95DD79E9BDc60/token-transfers#transfers

We are now moving funds from the S1 Treasury to the Minion here:
- https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158/proposals/47

**Comment by nintynick** [comment]
Airdrop complete!

https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158/proposals/48

https://blockscout.com/xdai/mainnet/tx/0x062df65b31cb32bb31689fee3c78162e6d5ba539a436ac72af8bc90ca823296c

**Comment by nintynick** [comment]
I submitted a proposal to transfer the remaining balance to the Raid Guild DAO Raid Incentives minion. 
https://app.daohaus.club/dao/0x64/0x10e31c10fb4912bc408ce6c585074bd8693f2158/proposals/49

This vote passed and 800,001 RAID has been transfered to the RG DAO Raid Incentives minion https://blockscout.com/xdai/mainnet/address/0x10E31C10FB4912BC408Ce6C585074bd8693F2158/tokens

<img width="1680" alt="Screen Shot 2022-01-23 at 12 09 20 PM" src="https://user-images.githubusercontent.com/10171948/150689688-ffc09325-a5c7-4714-8c6f-9c38a1ebc2f9.png">

Closing this issue.
