### ISSUE TITLE
RIP: Raid Commitment Staking and Bonus Rewards

### ISSUE THREAD

**Issue by nintynick** [raid-guild/RIPs#75]
# Project Idea
The goal of this RIP is to create a mechanism that incentivizes the completion of raids after they are committed to by raiders. To do this, we propose a simple staking and bonus system: stake to commit to a Raid (or RIP), get slashed if you don’t complete the Raid.

### Project Submitted by:
nintynick, @slgraham, @amsos, keating

## Summary
**MVP Process**
1. Raid party opts-in to doing commitment stakes
2. Raid party creates either:
    a. A Moloch DAO with a raid-specific minion used for staking, or
    b. A multisig
5. Each raider signals commitment by staking RAID on the commitment contract
    - Stake approximately ~5% of the total earnings you are expecting
6. Upon raid completion, Raid party requests RAID from Guild reward pool to their DAO or multisig for bonuses
7. Each raider then submits a withdraw proposal to the Raid-specific DAO or multisig for their initial stake + bonus
    - Proposals are manually approved by vote of the Raid party
    - "Slashing" just means that the staker's withdraw proposal is rejected by the DAO (similar to Championing process)
    - Reward formula = double your stake OR 5% of the total earnings you received from the raid, whichever is less

## Why should we build this?
- **Consistency of Commitments:** There have been some (but not many) explicit commitment failures in previous Raids. A couple instances where key people left a raid unexpectedly. We expect this to increase as Raid Guild increases in size
- **Cleric and Monk QoL:** Clerics and Monks would feel more confident in setting up raids and negotiating with clients on budget and timing if they could be more confident about the commitment of the Raiders they’ve found to work on the Raid
- **Raid Guild Scalability:** Better data about commitment history, and eventually availability. There may be more issues with Raider commitment the larger we grow
- **Adding Raid Completion Bonuses:** Generally, we want to test and establish ways to give Raiders rewards for completing Raids (including reputationally)
- **RAID Token Utility:** As a secondary goal, increase in RAID token price, via additional utility and demand for RAID token

## Anything else you'd like to add?
1. As we test the MVP, there are several key knobs to pay attention to and iteratively modify:
- Staking amount
- Bonus amount
- Number of of active stakes over time (to get a sense number of commitments)
- Number of slashing events

2. If this mechanism is successful and we are able to scale it up, we anticipate that we will also be able to solve the problem of having high quality data about Raider availability for Raids using a similar mechanism.

3. For additional details about the availability portion of the mechanism, as well context on the iterative development of this RIP over the last two months, see the working doc here: https://hackmd.io/AMDROH7gToSqELsOcLIKJg?both

## Raid Party Skills Needed
- Mechanism design
- Project management
- Smart contract development - (Phase 2 - not outlined here)

## Cost (in USD)
Phase 1:
Bonus pool for MVP - $325 = 5% of total rewards for RIP #72
Mechanism design - intended to be covered by Sustainable Ops distribution
Project management - intended to be covered by Sustainable Ops distribution

## Timeline
1 week - implement MVP
3 weeks - track #72 
1 week - allocated bonuses, MVP retro

**Comment by nintynick** [comment]
Proposal to Raid Guild DemoNick Minion to send RAID to S1 DAO passed and can be found here: https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/265

**Comment by nintynick** [comment]
ECWireless created the multisig set up for the HireUs Improvements RIP: https://gnosis-safe.io/app/xdai:0xb336A3fa25Da137D508D1b1246ecaF1D88cE83B0/balances

They are planning on kicking this RIP off starting January 10th. 

I will submit a proposal to the DAO for this RIP when I return from being offline on 1/4.

**Comment by amsos** [comment]
Very excited to see this up and running.

@slgraham @dekanbro  I know I'm already thinking too far ahead, but would be interesting to see how we could incorporate a shaman into this

**Comment by nintynick** [comment]
Two opportunities for improvement:
- staking on raids that are hourly and that don't have a fixed sum prior to the start of the raid
- staking on grant-based raids (amounts paid up front)

**Comment by nintynick** [comment]
Stake has been made by the Consultation Queue RIP team:

## Staking @ $0.022/$RAID (on 1/11/22)

@Warrior Prince  - 5% of $3,000 = 6,818 $RAID
@ECWireless  - 5% of $1,800 + $500 = 5,227 $RAID
@proofoftom  - 5% of $1,200 = 2,727 $RAID

Commitment Staking Safe: https://gnosis-safe.io/app/xdai:0xb336A3fa25Da137D508D1b1246ecaF1D88cE83B0/balances

**Comment by nintynick** [comment]
Proposal submitted RG DAO to match the 14772 RAID staked in the Gnosis Safe: https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/294

**Comment by nintynick** [comment]
Proposal passed and executed, 14772 RAID transferred to the gnosis safe (tx: https://blockscout.com/poa/xdai/tx/0xd111d8464efde06fea90a529e119c299f6ee50da4cae8fff1c987ec5cfcff97e)

**Comment by nintynick** [comment]
## Retrospective
Overall the mechanism was a success! One person abandoned the RIP, and the two other people split that person's stake + bonus for their troubles.

### What happened (after the last post here on Jan 26)
1. On Feb 11th, ProofofTom abandoned the RIP (by not completing his work by the deadline that he committed to) and lost his stake of 2727 $RAID
2. Warrior Prince and ECWireless completed the RIP, including ProofofTom's portion of the work
3. On Mar 22nd, ECWireless submitted a proposal to the DAO for pay for the completed RIP ([DAOhaus link](https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/316))
4. On Mar 24th, Warrior Prince and ECWireless withdrew their stakes + bonuses from the multisig ([Warrior Prince tx](https://blockscout.com/xdai/mainnet/tx/0x18ebf6ca16a91be7dbaab6cc272ee397b40b3635ec6065357ce20437ab8d9b5a/), [ECWireless tx](https://blockscout.com/xdai/mainnet/tx/0x5a2aa100d0c5f669e7ecfd53eed661488dac569e081dd4528d023d23ca58c749/)) 
5. On Mar 27th, the proposal to pay for the completed RIP was passed by the DAO with no votes against ([DAOhaus link](https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/316))
6. On Mar 30th, after coming to the Token Talk meeting and getting the support of the Token Talk team, Warrior Prince and ECWireless split ProofofTom's stake + bonus (2727 $RAID each, [Warrior Prince tx](https://blockscout.com/xdai/mainnet/tx/0x7b021c41f951b79940c04b21da8a9bfc3583ee4b4b0fb383ddcdfa23b79f0902/), [ECWireless tx](https://blockscout.com/xdai/mainnet/tx/0x90ec3acd5292164c14eb84162049a50b60aa9d1cdd82e16f22d8742e80843045/))

### Observations
- The multisig (which was used as an MVP replacement for a staking contract) was a 2/3. Had more than 1 person abandoned the project, it would have been impossible to move the funds
- Total pay for the project was 6500 as expected (which was used for RAID bonus calculations)
- Pay for Warrior Prince was 3000 WXDAI as expected
- Pay for ECWireless was 3300 WXDAI, compared to original estimate of 2300. (Assumption: ECWireless took on ProofofTom's work, which was originally slated for 1200 WXDAI)
- Pay for Christina was 201 WXDAI, who did some copy editing and was not originally included in the RIP

### Questions for possible improvement
1. What is the right % of projected revenue to create the right disincentive for abandoning the project? (ECWireless suggested that 5% might be too low)
2. Is it okay for the bonus amount to be lower than the staked amount?
4. Should we create an alternative MVP to the 2/3 multisig that handle multiple abandonments on the same project? (Eventually, this could be its own staking contract and may not be an issue)
5. How might we handle staking on raids that are hourly and that don't have a fixed sum prior to the start of the raid?
6. How might we handle staking on grant-based Raids, where the payments are distributed upfront?

### Next steps
- Determine the next experiment to run (possibly: 3 RAIDs and RIPs simultaneously, with adjusted stake %)
- Run the next experiment
- Poll the guild on interest and willingness to use this staking mechanism as an opt-in tool

**Comment by nintynick** [comment]
### Notes from Token Talk retro discussion on 4/7:
Overall:
- ECWireless shared that Warrior Prince send Christina some of the RAID bonus he received to her (Christina and Warrior Prince agreed on the WXDAI payout, then treated this more like a "tip"). Maybe we should ask him for his motivation.

Question 1:
- Definitely more than 10%
- Considering the anecdote from Aaron about how the school added a fee for leaving your child late, and more people started to do it
- Want to avoid something people think of as "this little fee they pay to get out of work"
- Could it be something more scarce, like DAO shares or some other form of reputation?
- Maybe a three-strikes rule for the same? Public badge, goes away after some set period of time
- What is the penalty? (Can't do raids for a quarter, guildkick, etc.)
- This brings us back to larger scope of discussion to, not just commitment, but Availability and Commitment
- What is reputation? -> tabling as a separate conversation
- Could just be a public badge of how many times someone bailed (and maybe how many they completed?) - Discord role, included in Dungeon Master
- One of the properties of this system is to create a more visible and legible marker of this things happening
- People can use this in their own way to determine if they want to work with them (perspectival reputation)

Question 3:
- Stay with the multisig for now, until we have a better idea of what we want the staking to do
- If we're worried about people getting stuck, we could make a minion signer that helps with these

Question 4:
- Could take it from pay?
- How often does this come up?
- Could be solved by the Availability staking component - so it's a portion of your periodic capacity
- Stake could be for a week, and be a rolling stake
- For this category, it could be a higher stake for the pay period (like 40-100% of 1 pay period, relative to 5-20% of the total project, to cover the costs of losing you - knowledge transfer, replacement, onboarding, etc)

**Comment by launchninja** [comment]
I like the idea of having reputation listed inside of Dungeon Master as stats. Kind of like a baseball card or Pokemon card. Total number of RAIDs/RIPS, completions, roles, and maybe even project size/billing. Would give more insight into what type of work they can do and at what level. For example, this person is good on small jobs, but can't complete the big projects.

**Comment by ECWireless** [comment]
Quest 2:
- In order to not drain RG's supply of $RAID, I would push to keep the bonus around 5%, even if the slash percentage is much higher
- Overall, I think people should think of staking as a way to disincentivize abandoning raids vs a way to incentivize completing raids

**Comment by slgraham** [comment]
Increasingly I feel like bringing in the capacity/bandwidth component is going to help in several ways:
- Increase the weight of slashing, since you now have less capacity to earn income from Raid Guild
- more naturally tracks contributions to a raid, in particular for on-going/retainer raids
- also has the side benefit of creating an availability registry for clerics and monks to use when spinning up a new raid

Of course, as originally discussed, the challenge is bootstrapping and adoption. I don't yet have a good recommendation for how to approach that.

**Comment by plor** [comment]
I think playing with the percentage required to stake will help us find the right equilibrium, though perhaps this isn't fully stable and will need to be ongoing based on some metrics that we continually assess. In addition to this, if we have a neutral stake at 20%, perhaps it could go down as reputation (raids stuck out/total raids) increases and go up as reputation decreases (10-30% stake?)

I think positioning this on a D&D lawful/neutral/chaotic scale would be good for lore and a great addition to a stat sheet that could be represented in Dungeon Master. Sometimes we need the chaotic raider to complete the team but we know what we are risking.

Lastly, because we are dealing with reputation, a redemption arc is necessary. If someone has a hard time and flakes on a couple raids such that they are not chosen for future raids, there should be a mechanism for them to prove that they are not a liability on the raid and redeem their place as a reliable raider. I don't know how this would play out, but I think it is a necessary feature.

**Comment by amsos** [comment]
Whoops - sorry for the accidental close... 😅

I agree that trying to tie this to reputation a bit could be a huge unlock.  Whether that's just a three strike system or something more complex.

that said, I 100% agree with @plor that we need some kind of redemption arc.  Have people seen non centralized redemption arcs before?

**Comment by nintynick** [comment]
@plor I love the idea of using the D&D archetypes for the role. However I would lean more toward Good-Neutral-Evil than Lawful-Neutral-Chaotic. I think some people pride themselves on being Chaotic, but nobody really wants to be Evil.

With that said, I think we could roughly think of this as In Good Standing - Not In Good Standing - In Bad Standing. Building on the redemption arc, here's my first pass thinking for the evolution of the mechanism:

**Good**
- Full permissions as a Raider and Guild member
- All Raiders begin in Good status (when they join the guild, and when this mechanism is implemented)
- Can stake 20% of projected income on Raids to receive 5% bonus income in RAID
- If Raider abandons a Raid, moved to Neutral status

**Neutral**
- Discord Role
- Must stake 20% of projected income to join a Raid (still receives 5% bonus income in RAID for Raid completion)
- Must receive stake back after completion of each of two Raids to move back to Good status
- If Raider abandons a Raid, must receive stake back after completion of two **additional** Raids to move back to Good status
- If Raider is five or more Raids "in the hole," moved to Evil status

**Evil**
- Discord Role
- Not able to join raids for X period of time (3 months?), then moved back to Neutral status with two Raids "in the hole"

What do you folks think?

**Comment by plor** [comment]
@nintynick Yeah, this might be the correct axis. I was trying to stay away from it partly because the recognition of "evil" as a possible trait as part of a normal process seems weird. If we are a band of "good" raiders, having an "evil" member amongst us should cause more than just a timeout.

I also think that starting in "neutral" allows someone to prove that they are more reliable and gain the reward for doing so. Also we could graduate it a bit more (75% neutral/25% lawful), which would allow for smaller shifts in the reward/punishment. Starting everyone at max means they only have something to lose.

Maybe we need both axes from D&D archetypes, it depends how we want to portray them.

**Comment by nintynick** [comment]
Running a second prototype of this as part of RIP 89: https://github.com/raid-guild/RIPs/issues/89

**Comment by plor** [comment]
We should write this RIP up as a `.md` document in the proposals directory to have a permanent record of the process that can be added to with additional phases. I'm going to move this to final as we've concluded the MVP of this initiative.
