### ISSUE TITLE
RIP: Discord POAP Onboarding Bot

### ISSUE THREAD

**Issue by aenhsaihan** [raid-guild/RIPs#76]
### Project name
> POAP Quiz Bot (open to change)

### Team members 
> @kai.thompson @bluewhiteorange 

### What project are you building 
> The purpose of the POAP Quiz Bot is to facilitate the onboarding process for prospective DAO members. It can also be extended to streamline DAO interaction to provide a greater sense of community and reward users with tangible proof of participation.

### Why did you decide to build it
> The idea sprouted from a desire to participate in RaidGuild's cohort process but later grew into a means to improve the suboptimal onboarding of DAOs. Through a simple gamified process, there lies the potential for a streamlined industry-standard of DAO participation.

### User Flow

![poap-bot-flow](https://user-images.githubusercontent.com/4359103/146285731-4e654596-69a3-46f9-88ac-62dbe32e9731.png)

### Anything else you'd like to add?

> Possibly can be used to designate roles based on the passage of certain quizzes.

### Screenshots

> Not final form

<img width="415" alt="Screen Shot 2021-12-09 at 11 38 58 AM" src="https://user-images.githubusercontent.com/4359103/146284244-4af48d2e-07ef-46c3-9fee-8c19302989fe.png">
<img width="363" alt="Screen Shot 2021-12-09 at 11 39 45 AM" src="https://user-images.githubusercontent.com/4359103/146284257-52ac11e8-d476-44a3-af64-bccd1e646a2e.png">
<img width="538" alt="Screen Shot 2021-12-09 at 11 40 27 AM" src="https://user-images.githubusercontent.com/4359103/146284265-0036d5de-3947-455f-8708-46b12c6e6854.png">

### How long will it take 
> 2 weeks

### How much funding are you requesting  
> 3k DAI

### Tools

* Discord.js
* MongoDB
* POAP

**Comment by plor** [comment]
This was moved to yeeter funding correct? Should it be removed from the RIP board?

**Comment by plor** [comment]
I'm cleaning up this board, will close as not doing, but feel free to reopen if this should be considered again.
