### ISSUE TITLE
Raid Guild’s Notion Documentation Hub

### ISSUE THREAD

**Issue by govinda108108** [raid-guild/RIPs#80]
# **Raid Guild’s Notion Documentation Hub**

![Untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fcc7f4ca0-a5fe-48e4-b449-712e4c1026d3%2FUntitled.png?table=block&id=4a5c358a-482c-4211-b75a-f7ed6e7259af&spaceId=f3816bc2-dc44-4442-a155-c7b3449a355a&width=2000&userId=fe882376-1dc6-462b-8aac-17103f6cdf2a&cache=v2)

## **The Demon** 🕷️

![Untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F50b58d95-d50a-4c15-92f7-757c90945a97%2FUntitled.png?table=block&id=b8cfa1cf-8fea-4053-85fb-57286b3294bb&spaceId=f3816bc2-dc44-4442-a155-c7b3449a355a&width=2000&userId=fe882376-1dc6-462b-8aac-17103f6cdf2a&cache=v2)

🕷️
Moloch's minion Shelob is obstructing progress (especially amongst newcomers) with her webs. Frodo and Samwise, for instance, are separated at Raid Guild, struggling with fragmented information, difficult discord navigation and handovers

Fragmented Information: Different google docs, hackMDs are spun up and shared on discord channels, creating information silos. 

Difficult Discord Navigation: In order to find the information they need, members must navigate different discord channels, which are constantly moving (it’s like working on a slot machine!). 

Distributed Handovers: Different members are working on similar projects, or looking to iterate on someone else’s project. That person may not be locatable/contactable, and important threads may be unaccessible or archived. Contributors are always coming and going, and need to be brought up to speed quickly on project status and documents and assets. 

🕸️ 🕸️ 🕸️ 

The result? Guild members are kept from the information they need. 

Overheard on Discord: 

“What was that link again?” 

“I can’t find the hackMD?”

“Who do I ask about this?”. 

The Raid Guild handbook contains useful, but incomplete information and is not a working document. 

## **The tools at our disposal**

Notion connects teams, projects, and docs — so we can bust silos and move as one.

- Ability to create a hierarchical document, in which a user can navigate through **ALL** Raid Guild’s documentation
- Able to create an attractive landing pages,
- Spin up project pages that contain relevant HackMDs, project management kanban boards that different contributors can access at any time
- It’s what you see is what you get interface makes it easy for non-technical people to make additions (versus Markdown)

Metagame are killing it in the documentation game and acted as an inspiration for this RIP. 

- Metagame notion page: [https://www.notion.so/Welcome-to-MetaGame-v2-349d9b6434d543b48539bccabf10b60a](https://www.notion.so/Welcome-to-MetaGame-v2-349d9b6434d543b48539bccabf10b60a)

Hack MDs are Raid Guild’s mainstay, and they can be contained within a Notion page. 

## The quest

This RIP is requesting 1300WXDAI retroactive funding for a centralized documentation hub for Raid Guild. [See here](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a) for the finished project. 

This documentation can act as A) a centralized source of knowledge B) a project management tool and C) a working document for Raid Guild members and apprentices.

There are so many amazing projects and resources contained within the Raid Guild Discord server. This document is a home for all of them and a place of shelter for lost Raiders! 

By centralizing our information, A) more Raiders can get more of the information they need, B) waste less time searching for things, and C) increase collaboration through open documentation and project management.  

This documentation was first compiled by Govinda during his cohort season, to avoid the maze of Discord channels and to help fellow lost cohort members. As the need arose for the documentation that was being created during the cohort, it was then expanded into a fully-fledged project. 

## **Raid Party**

Season 3 apprentices: Govinda, Zberwaldt, uschtwill, BorrowLucid,  

## **Quest set in motion**

All of the following activities have been completed. 

Part 1: Gather all Raid Guild documents from discord, the forum, DAOhaus, the handbook:

- Essential documents (e.g. [discord channel guide](https://www.notion.so/Discord-Channels-Guide-17aebbe49ab547398950ab9899850a3e), [meeting notes](https://www.notion.so/235226f3497a4efd83d11e9b5ae53f16))
- [FAQ](https://www.notion.so/FAQ-135725094d6449efb781feb98066c095) for new users
- [Quests](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a) for first users: [Onboarding guide](https://www.notion.so/1-Quick-Start-Guide-5-mins-d6d0f3d5a31d4dadac6dd259cd411baf) (related seperate RIP)
- Work-related docs ([discord bot guide](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a), [brand assets](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a), calendar, DAOhaus)
- [Useful resources](https://www.notion.so/Full-List-Links-Resources-5680038dfc724d1bb86748e9c8247b6a) for Guild members

![untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3814e22b-ffa2-4c35-b4bc-8f89a72e622f%2FUntitled.png?table=block&id=d908d8c3-46dd-40f4-a7ac-8c77031cc6ec&spaceId=f3816bc2-dc44-4442-a155-c7b3449a355a&width=2000&userId=fe882376-1dc6-462b-8aac-17103f6cdf2a&cache=v2)

Part 2: Create a [documentation hub](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a) for RG members and apprentices, that can be built on top of and integrated with current documentation. 

- Includes a [navigable landing page](https://www.notion.so/Raid-Guild-Landing-Page-b019b430590c4b65a504704f257ac83a), with an overview of all documentation.
    - User story: Instead of Frodo searching through discord channels for what he is looking for, asking another member or giving up, he knows he can head to the landing page and find what he's looking for.
    

![Untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fa1a86e9f-745c-4cee-8191-2ecd36cef397%2FUntitled.png?table=block&id=b0d1d225-4f87-4167-8a1c-3e5682853aad&spaceId=f3816bc2-dc44-4442-a155-c7b3449a355a&width=2000&userId=fe882376-1dc6-462b-8aac-17103f6cdf2a&cache=v2)

Part 3: Collect cohort project hackMDs and store on [project page](https://www.notion.so/712c8dcbc776457f9a6db2ae15338d77) which can facilitate projects through time, e.g for successive cohorts. 

- This page can also be used for guild members to find apprentices willing to work.
- Can be used for next season cohort projects
- In the spirit of web3, this increases the composability of Raid Guild projects, so we can build on top of each others work.
- User story: Samwise Gamgee has just started on a new Raid Guild cohort and he is eager to contribute. He heads to the projects page and sees a project the last cohort worked on. He sees the future features of the project, thinks one is awesome and decides to build it. He gets in touch with the previous project team, who provide him feedback and guidance on how to implement it. 

![Untitled](https://user-images.githubusercontent.com/93854208/148710887-bcfac744-7704-4ca0-97dd-335c183f4d04.png)

## Breakdown

This is a retroactive funding proposal for 1300WXDAI for the documentation hub for Raid Guild. 

900WXDAI creating and compiling content

-condensing season 3 FAQs, gathering needed info 

-combing discord and collecting links and resources, compiling into a document. 

-collecting project hack MDs from season 3 cohort 

150 WXDAI design

-designing and building landing page 

250WXDAI project management

-communicating with members and project documentation

**Comment by plor** [comment]
@govinda108108 I think you mentioned moving this work into the hackmd documents. Do you want to continue with a RIP for this work or roll it into the healers RIP that will be forthcoming?

**Comment by plor** [comment]
We've moved to charmverse. Closing.
