### ISSUE TITLE
Raid Guild Design System Development and Storybooks

### ISSUE THREAD

**Issue by 0xShred** [raid-guild/RIPs#81]
# Project Idea

## Summary
Create a Chakra theme and react components with styles started in the [RG Styleguide](https://github.com/raid-guild/RIPs/issues/71). From those components create a Storybook UI library for Raid guild members to reference when building frontend applications. 

### Project Submitted By
0xShred & Scottpreneur

## Why should we build this?
- Simplify the development process
- Save time
- Create congruent brand assets to be used across Raid Guild applications
- Reduce confusion
- Guild new members

## Anything else you'd like to add?

Not at this time.

## Deliverable

- Updates to the [Raid Guild Design System](https://github.com/raid-guild/design-system)
- Create a Chakra theme and react components with styles started in the [RG Styleguide](https://github.com/raid-guild/RIPs/issues/71). From those components create a Storybook UI library for Raid guild members to reference when building frontend applications. 

## Raid Party Skills Needed

- Web application development and product development
- Web design
     - Figma
     - UX

- Frontend development
    - JS, TS, React, CSS, SCSS
    - Chakra
   - Web accessibility

## Cost (in USD)

$8,000

**Comment by plor** [comment]
I moved this to final to clear out the board. Updates and follow-on work is welcome.

**Comment by scottrepreneur** [comment]
Extension one completed https://github.com/raid-guild/design-system/projects/1
