### ISSUE TITLE
RIP: ShillShop Systemization Phase 2

### ISSUE THREAD

**Issue by launchninja** [raid-guild/RIPs#86]
# Project Idea

### Project Submitted By

John (launchninja)

## Summary

Create all the processes and Trello boards ShillShop needs to “standardize” the way we tackle client work.

This will give ShillShop the ability to scale faster (and easier) as we take on more clients and build our talent pool. Most importantly, it will prevent bottlenecks and allow Raid Guild apprentices to more easily integrate with ShillShop and complete client work.

## Why should we build this?

- More certainty and consistency of upcoming marketing work (can earn full income from RG and leave “job” behind)
- Increase efficiency and output of ShillShop
- Increase quality of deliverables to clients
- Complete client projects faster - which leads to happier clients
- Completing bigger/more client work will grow the RG treasury so that more RIPs and internal raids can be funded

## Anything else you'd like to add?

Full details of Phase 1 (completed) and Phase 2 are located here: https://hackmd.io/l9pgahNhTu-Wl1Ym8EKzJw

## Raid Party Skills Needed

- Account Management
- Project Management
- Web Design / Dev
- SEO
- Content Creation
- Video Production

**Team:** John(launchninja), brendan, degeneroach, willdro

## Cost (in USD)

\$6000 (40 hours @ $150/hr)

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/330

Moving to Final since the funds have been transferred, it would be useful to use this issue or a `.md` file to present the deliverables when complete (also a show 'n' tell in Round Table perhaps).
