### ISSUE TITLE
Portfolio Uplift Phase 1 - UX, Content and Requirements

### ISSUE THREAD

**Issue by osterby** [raid-guild/RIPs#88]
# Portfolio Uplift Phase 1 - UX, Content and Requirements

### Project Submitted By

`@winevault.eth` (Aaron Osterby) with support from `@Dao Jones` and `@E2T`

## Summary

Some Season 4 apprentices have taken on the [Dework prompt](https://app.dework.xyz/raid-guild-season-4/season-4?taskId=d981d230-8b2c-48cc-b823-f79df66885de) to refit the Raid Guild Portfolio.

The [project plan](https://hackmd.io/01-eceQ7Tua37fhJvHIXSQ?view) outlines the approach. It is socialised and a team is on board to execute Phase 1, which this RIP proposes to commence.

## Why should we build this?

There is concern expressed among Guild Members that consultation conversions should to be healthier. 

It is known that the Raid Guild Portfolio requires a redesign to contribute more effectively to filling the Raid Guild consultation queue. The portfolio content hasn’t been updated in a long time, doesn’t reflect recent Raid Guild activity, and could communicate broader scope, insight, and credibility to prospective clients, which in turn would further increase demand for services.

### Phase 1 - UX Audit
- Heuristic evaluation of current site
- Proto Persona Development for Design Sprint
- Current Usage data analysed, if available
- Deliver UX Artefacts / Guidelines

### Phase 1 - Content Development
- Document the Headline raid in case study with appropriate image artefacts.
-- Interview Headline Raiders, write content and collect assets
-- Write and edit case study with relevant image assets included

### Phase 1 - Requirements
- Deliver documented portfolio requirements
- Deliver documented content management requirements

## Raid Party Team

- Project Management - `@winevault.eth`
- UX - `@wallfacer`
- Content Development - `@stephenpdiesel`

## Cost (in USD)

\$2400

### Governance

The project is requesting funding into the [project DAO](https://app.daohaus.club/dao/0x64/0xfc93639e0a6b56ecc65d8e113beb260324194dc9/members).  There is controlling interest in the DAO by two Raid Guild sponsoring members.

### Phase 2 
- Design Sprint
- Technical Planning and Estimation

### Phase 3 
- Build and Test
- Ship
- Cake Party
- Hypercare Period

**Comment by plor** [comment]
Was this ever placed under consideration?

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/344

**Comment by osterby** [comment]
This was accepted as complete by 0xhanvaled, E2T and DAOJones.

Deliverables: 
https://www.figma.com/file/70ypP12ryjUxMz1HzFFLAU/RIP-%2388---Portfolio-Site-UX%2C-Content-and-Planning?node-id=0%3A1

Video walkthrough of the FigJam is available internally as well.
