### ISSUE TITLE
RIP: Champion staking process improvement

### ISSUE THREAD

**Issue by plor** [raid-guild/RIPs#90]
# Champion Staking process improvement

### Project Submitted By

plor

## Summary

This is a follow-up to the Champion Staking experiment to include the feedback from the retrospective (#87). In addition I will be building out a process to better track the champion process through the different phases. This does not include any changes to the rewards or further assessment of the experiment. I hope it might assist in this process when it occurs.

The main point of contention is that we should move the membership proposal to the end of the champion process. This means that if the success criteria are not met, the championee will remain an apprentice and the champion will be slashed.

The deliverables here are:
  - [ ] An update of the documentation to change the process and clear up some language
  - [x] Move the reporting of championing to Github with the creation of a new issue template
  - [x] Add a project board like the RIP board to manage the process

## Why should we build this?

Just as we want to view the progress of RIPs being proposed and worked on, we should better track and follow the progress of new member onboarding. The champion process has been successful in adding accountability to bringing in new members. This will just add a bit more visibility to that process.

## Anything else you'd like to add?

This process is meant to be superceded at such a time as the process is built into an application.

## Raid Party Skills Needed

- Just me

## Cost (in USD)

0

**Comment by mackbowes** [comment]
Great idea :)

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/352

**Comment by plor** [comment]
https://github.com/raid-guild/RIPs/pull/91 for issue template

**Comment by plor** [comment]
https://github.com/raid-guild/handbook/pull/69 for handbook updates.

**Comment by plor** [comment]
Changes to handbook are awaiting larger effort to improve handbook.

**Comment by plor** [comment]
The handbook updates are delivered to the necessary place, I'm going to mark this complete with the #92 merge.
