### ISSUE TITLE
Govinda (scottrepreneur)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#93]
### Championee

Govinda

### Champion

Scottrepreneur

## Summary of work to date

Season 4 cohort presentations and preparation

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[Staking Tx](https://blockscout.com/poa/xdai/tx/0xe96e9a444bfdbe177399eb17f770325af659a2ba28b2be54de24b49a14c4a5c6)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

## Post date (catch up with current stakes)

March 24, 2022

**Comment by plor** [comment]
@scottrepreneur this has been 91 days, you can make a proposal to claim your rewards.

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/371

**Comment by plor** [comment]
https://blockscout.com/xdai/mainnet/tx/0x14d03d53dd2797815674c56d678814c709d6c15c47961b0d9a0e733415531ddb
