### ISSUE TITLE
Degenroach (kerp)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#94]
### Championee

degenroach

### Champion

kerp / mac (@0xhanvalen)

## Summary of work to date

They gud

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[Staking tx](https://blockscout.com/xdai/mainnet/tx/0x77f11b83671c4fe35bc1436d4f0f14a9db521c2e0ddb8d181c06b3058ab15624)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

## Post date (catch up with current stakes)

March 30, 2022

**Comment by plor** [comment]
Kerp, it has been 85 days, you can claim your reward at any time.

**Comment by ECWireless** [comment]
Closing since this is over a year old
