### ISSUE TITLE
Stargarden (penguin)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#95]
### Championee

stargarden

### Champion

penguin

## Summary of work to date

Got my first happy raid guild client and project under my belt - lfg

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[Staking tx](https://blockscout.com/poa/xdai/tx/0xb59ecb11f7b04c3230cd720fd68fb717900b1adfdb88f016a972c92a29711664)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

## Post date (catch up to current stakers)

April 12, 2022

**Comment by plor** [comment]
penguin, it has been 72 days, you can make a proposal to claim your reward.

**Comment by ECWireless** [comment]
Closing since this is over a year old
