### ISSUE TITLE
ApeironCreations (mkdir)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#96]
### Championee

ApeironCreations

### Champion

mkdir

## Summary of work to date

joined in season2, mostly been lurking but wants to contribute

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[Staking tx](https://blockscout.com/poa/xdai/tx/0x2ef85c1f88e9e83a694e41d675a50882aab6f0f476e9b3a48a653090f767e0f5)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

## Post date (catch up to current stakers)

May 05, 2022

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/362

**Comment by plor** [comment]
https://blockscout.com/xdai/mainnet/tx/0x5665a40ed93e7ce5629e8280718d05bb36a7911484019528e64277d48f22f68e
