### ISSUE TITLE
jp4g (scottrepreneur)

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/RIPs#97]
### Championee

jp4g

### Champion

scottrepreneur

## Summary of work to date

Originally met at EthDenver and will be a great asset on the product/project side as we're bringing on some new projects.

### Applicant source

 - [x] Cohort process (`25,000 RAID` stake)
 - [ ] Non-cohort (`50,000 RAID` stake)

### Link to staking transaction (to `0x45b49f854eebadbdb59ede30fe5b37ba56a0f26c`)

[Staking tx](https://blockscout.com/xdai/mainnet/tx/0x3b239a66056d2dc45bf78abdb1d7747188c37f3e8daab979d09fbb962ac7f6aa)

## Anything else you'd like to add?

Not at this time.

## Success criteria

Comment within this issue, before moving to membership, the realization of the
following success criteria:

1. Apprentice period of 60 days.
2. Successfully join at least 1 raid or RIP. This includes raids or RIPs
   completed as well as raids or RIPs still in progress (provided the
   apprentice is in good standing on that project).
3. Attend at least 2 core Guild meetings, currently includes Roundtable, Raider
   Roundup, or Token Talk.
4. Demonstrate shared values with the Guild (at the discretion of the DAO).

## Post date (catch up with current stakers)

May 1, 2022

**Comment by plor** [comment]
This has been more than 60 days now. You can make the proposal to have your stake returned plus the reward.

**Comment by plor** [comment]
https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/proposals/371

**Comment by plor** [comment]
https://blockscout.com/xdai/mainnet/tx/0x14d03d53dd2797815674c56d678814c709d6c15c47961b0d9a0e733415531ddb
